### ISSUE TITLE
Why does JavaScript need a style guide?

### ISSUE THREAD

**Issue by ColemanGariety** [airbnb/javascript#102]
One of my favorite parts about the JavaScript community is that people choose to write it in so many different ways.

Why do you want to ruin that with a style guide? 

Imagine if when Picasso was learning to paint, we told him what style he should paint in. Would we have cubism?

**Comment by simoniong** [comment]
@hshoff  really amazing example! Love it!

**Comment by cliffjones** [comment]
It always strikes me as silly when people make arguments against standardization because they feel like it infringes on their artistic rights. You're free to be as avant-garde as you want on your own time.

Following the painting analogy, it's worth pointing out that Michelangelo didn't paint the whole Sistine Chapel ceiling himself. He managed a bunch of junior painters who all had to rigidly adhere to the "Michelangelo style" so the final product would hold together as a unit.
