### ISSUE TITLE
Consider adding no-template-curly-in-string rule

### ISSUE THREAD

**Issue by McGiogen** [airbnb/javascript#1049]
It is a common and easy mistake to write string templates with single quote char `'` instead of backticks \`, especially when you are fixing a `prefer-template` error, converting a string to template but forgetting about backticks.

Adding `no-template-curly-in-string` rule can help to find those errors.

**Comment by ljharb** [comment]
Since I'm one of the ones that suggested that rule in the first place (https://github.com/eslint/eslint/issues/5850 / https://github.com/eslint/eslint/issues/6186 ), I'm definitely planning on enabling it prior to the next semver-major release. Our release process ensures that all rules are configured, so it will definitely be covered.
