### ISSUE TITLE
Higher order functions and the arrow-parens rule

### ISSUE THREAD

**Issue by dlwalsh** [airbnb/javascript#1082]
The `arrow-parens` rule requiring parentheses for blocks and no parentheses for one-liners takes no account of higher order functions.

I find it downright bizarre that I should be required to write code like the following:

```js
return next => (action) => {
  // etc
};
```

I don't know whether this is a config issue or an eslint issue.

**Comment by ljharb** [comment]
This is definitely our config and our styleguide. A function with one arg that's using implicit return must omit the parens; any function using explicit return must include the parens.

**Comment by dlwalsh** [comment]
I don't understand why you've closed this. Do you really think it makes sense to write higher order functions in this fashion?

**Comment by ljharb** [comment]
Absolutely I do! I think this rule helps make clear what the arrow functions I'm looking at do. `a => b => c => d => { … }` is pretty confusing for anyone that isn't coming from Haskell or Erlang or similar, which is the majority.

**Comment by dlwalsh** [comment]
I don't see how `a => b => c => (d) => { … }` is any clearer.

**Comment by ljharb** [comment]
When you switch from implicit to explicit return in that chain, the parens help visually break apart the implicit part of the chain from the explicit part of the chain.

In addition, very importantly, it takes something that is developer choice (whether to omit or include the one-arg parens) and legislates it, so that there's only one correct way to write it for a given codebase.

This is the style we use inside Airbnb - you're more than welcome to override any part of our config in your own eslintrc, or to fork the guide and make whichever changes you like.

**Comment by dlwalsh** [comment]
For what it's worth, I'm not taking issue with either no parens for one line one arg functions or required parens for block body functions; I simply find the inconsistency jarring for higher order functions. Obviously you don't agree, so I'll leave the complaint there.

> This is the style we use inside Airbnb - you're more than welcome to override any part of our config in your own eslintrc, or to fork the guide and make whichever changes you like.

I realise this. But I hate fragmentation, so I prefer to avoid overrides. Hence I'll bring to your attention anything I see as anomalies. In this case what I thought was a bug turns out not to be.

**Comment by ljharb** [comment]
Just so I understand your preference - you'd prefer that the one-arg paren either be always required or always forbidden?

**Comment by dlwalsh** [comment]
I'm saying where there is a block body all the parentheses should be required, since it's not a true one-liner. i.e. `(x) => (y) => (z) => { … }`

**Comment by ljharb** [comment]
It's not about being a one-liner tho - single-arg implicit return can be on multiple lines too, depending on what it's returning. It sounds like you want a special rule for when the single-arg of an arrow function is chained with other one-arg arrow functions - which is a scenario that eslint doesn't yet cover.

**Comment by felixsanz** [comment]
@ljharb I'm with @dlwalsh and i've come here just to find an issue or create one xD

I don't know what does the parens have to do with the curly brackets here, they serve different purposes and they are **independent** from each other.

The only thing that depends on parens vs no-parens **is the number of arguments**. If 0 or >1, required. Else nope, please. It doesn't matter if there is a return or a block, **that doesn't have anything to do** with the number of arguments!

This is more like... if you want parens because of readability, because not everyone is haskell programmer (this is a bad argument), etc... just use parens everywhere no matter what! But why create this rule so special? It makes no sense.

**Comment by felixsanz** [comment]
Here is an example that doesn't make any sense:

```javascript
    ${headTags.scripts.map((script) => {
      if (script.src) return `<script src="${script.src}"></script>`
      return `<script>${script.content}</script>`
    }).join('\n')}
    ${headTags.links.map(link => (
      `<link ${Object.entries(link).map(([prop, value]) => (`${prop}="${value}"`)).join(' ')}>`
    )).join('\n')}
```

Where is the consistency between `(script)` and `link`? Looks so bad!

It should be always or never (i'm talking about single argument in function signature)

**Comment by TigerC10** [comment]
Just now found this issue myself, taking a look at:

```javascript
    // require parens in arrow function arguments
    // http://eslint.org/docs/rules/arrow-parens
    'arrow-parens': ['error', 'as-needed', {
      requireForBlockBody: true,
    }],
```
https://github.com/airbnb/javascript/blob/7e865a4e8ab5e26062fcdc9437166c6e1c269599/packages/eslint-config-airbnb-base/rules/es6.js#L25

Yeah, I gotta admit I'm a bit bewildered by `requireForBlockBody` being true.  But I guess I fall into the camp where `arrow-parens` are always required.  Helps me visually associate that arg to the arrow function rather than to the wrapping function.  1 char diff between arrow function and assignment is not sufficient for my tastes.

Thank goodness for overrides. 🙄
