### ISSUE TITLE
Why should strings be ' ' and not " "?

### ISSUE THREAD

**Issue by GurudayalKhalsa** [airbnb/javascript#110]

**Comment by theage** [comment]
One could use single-quote strings only if there are double quotes in the string, and use double-quote strings otherwise. It would still be consistent, though the rule maybe less obvious, and you lose an excuse for not double-quoting strings in many cases.

**Comment by ljharb** [comment]
The eslint rule allows for double quotes when it would avoid escaping backslashes.

However, since both straight quotes are typographically incorrect - you should be using curly quotes in prose - this is only a problem when working with strings of html, which double-quotes it’s attributes. Thus, it’s basically never a problem with correct code/text.

**Comment by Come2Daddy** [comment]
I just find that backticks are closer to single quotes than double quote and IMHO can sometime cause readability issues.
HTML fits (today) well in a backticks bloc as it allows for a clean multiline implementation without any collision with most common quote style (single and double).
