### ISSUE TITLE
imports/prefer-default-export idiomatic use

### ISSUE THREAD

**Issue by gabor** [airbnb/javascript#1135]
hi,

how is the case where a file grows from containing only 1 function to containing 2 handled best?

example:

let's say i have a file called `window.js`, which contains only one function, `showWindow()`.
it's imported as `import { showWindow } from 'window'`.

of course this goes against imports/prefer-default-export. how should this be fixed? i guess i move the code to `window/showWindow.js`.

if i do that, then my import becomes `import showWindow from 'window/showWindow'`.
now what happens when a want to create another function, `countWindows()` ?

2 possibilities:

A.
i move `showWindow` back to `window.js` and add `countWindows` there.
if i do this, now i have to find all the places that imports `showWindow` and change those imports.

B.
i create another file called `window/countWindows.js` and put the function there.
if i do this, it means that nearly all my files will only contain 1 function.

so i wonder, how does airbnb handle this?

**Comment by ljharb** [comment]
The best solution is `B` - not every file contains only one function, obviously, but that's the best default (there are clear exceptions: constants, flux action creators, etc).

If you export `showWindow`, the guide requires that you name the file `showWindow.js`. Thus, `countWindows` would live in `countWindows.js`.

**Comment by tleunen** [comment]
Hmm.. I'll usually go with a more generic filename containing the exported function while disabling the rule for a default export. For the exact reason you mention.

**Comment by ljharb** [comment]
@tleunen that's potentially a fine way to go also - it really depends on the use case.

I'm suggesting that the *default* be one function default exported per file - and that if you think carefully about a use case, and you need multiple exports, then great! Make an exception.

The point of the defaults is so that you _have_ to think about if and why you deviate - not that you can _never_ deviate.

**Comment by gabor** [comment]
@ljharb thank you for the information.

the thing i do not like about the approach is that you and up with different things based on past actions... what i mean:
- if i start `window.js` with both `showWindow()` and `countWindows()` , then it will be fine for the linter and everything is great
- if i start `window.js` only with `showWindow()`, the linter will complain and i will have to move it to a separate file, and later `countWindows()` becomes a new file

so here we are, in one case we have: `window.js`,
in the other case `window/showWindow.js` and `window/countWindows.js` simply based on past decision (did i start with one function in the file or two functions in the file).

while, the important thing should be whether having just `window.js` is better or having `window/showWindow.js` and `window/countWindows.js` is better right now.  though i do not know how this could be handled with a linter :)

**Comment by ljharb** [comment]
Yes, it should disable named exports - the problem is that named exports make sense for a few specific use cases, like reducers, action_creators, constants, exporting a wrapped HOC for testing, etc - and a rule that prevented all named exports would be too restrictive.

We try to make the linter cover as much as possible, but there are times when you do still have to read the guide and apply human judgement :-)
