### ISSUE TITLE
Publish new release to fix unmet peer dependency

### ISSUE THREAD

**Issue by einarlove** [airbnb/javascript#1138]
In the 12.0.0 release of `eslint-config-airbnb` the depencency for `babel-plugin-import` was bumped, but not in `eslint-config-airbnb-base`. This creates a conflict of unmet peer dependency.
```
| +-- eslint-config-airbnb@12.0.0
| | +-- eslint-config-airbnb-base@8.0.0
| | `-- UNMET PEER DEPENDENCY eslint-plugin-import@^1.16.0
| +-- UNMET PEER DEPENDENCY eslint-plugin-import@2.0.1
```

I believe this error is fixed a week ago in https://github.com/airbnb/javascript/commit/0bb3eb541203aee1b134bef06940557cf7a30007, but not released to NPM yet.

**Comment by ljharb** [comment]
Since v12 of the main config requires v8 of the base config, and both require v1 of eslint-plugin-import, there's no conflict unless you've manually and incorrectly updated eslint-plugin-import to v2.

You're correct that a v13 of the main config that depends on v9+ of the base config is not yet released - that's intentional, as I'm waiting on a number of bugfixes in some dependencies.
