### ISSUE TITLE
react-a11y rules require object input, not array

### ISSUE THREAD

**Issue by arsenypoga** [airbnb/javascript#1212]
Eslint throws errors about invalid configuration for input values in react-a11y
The input value in:
`'jsx-a11y/anchor-has-content': ['error', ['']]`
should be:
`'jsx-a11y/anchor-has-content': ['error', {components: ['']}],`
[https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-has-content.md](url)
For 
`'jsx-a11y/href-no-hash': ['error',['a'] ],`
where it should be:
`'jsx-a11y/href-no-hash': ['error', { component: ['a'] }],`
[https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/href-no-hash.md](url)

**Comment by arsenypoga** [comment]
Another one at:
`'jsx-a11y/label-has-for': ['error', ['label']],`
should've been:
`'jsx-a11y/label-has-for': ['error', {components: ['label']}],`
Another one at:
`'jsx-a11y/heading-has-content': ['error', ['']],`
Should:
`'jsx-a11y/heading-has-content': ['error', {components: ['']}],`

**Comment by ljharb** [comment]
@arsenypoga this is intentional. `eslint-config-airbnb` is only compatible with v2 of `eslint-plugin-jsx-a11y` right now - if you use the `npm install` command in the package readme, you'll get the proper version.

In master, all these rules are already updated to be compatible with v3 of `eslint-plugin-jsx-a11y` and not yet published - but in the meantime, please downgrade to v2.

**Comment by arsenypoga** [comment]
Ok, I see. Well, I switched the values in he jsx-a11y config, and Eslint doesn't have errors anymore, so I can call it success anyways.

**Comment by ljharb** [comment]
Just published v14.0.0 of the main config, and v11.0.1 of the base config.

(#1162, #1166, #1182, #1186, #1207, #1212, #1222)
