### ISSUE TITLE
QUESTION: react/jsx-no-bind

### ISSUE THREAD

**Issue by ButuzGOL** [airbnb/javascript#1231]
What do you think about this way of written instead of bind in constructor ?
```
class Foo extends React.Component {
  foo = () => {
    doSomething();
  }

  render() {
    return <button type="button" onClick={this.foo}>blah</button>
  }
}
```

**Comment by ljharb** [comment]
Nope, that's less efficient, because instead of the meat of the function being on the prototype, and the own property merely being a bound form of the (optimized) prototype function, the entire function is created wholesale for every instance.

In other words, using a class property with an arrow function is equivalent to `this.foo = () => { doSomething(); };` in the constructor - not `this.foo = this.foo.bind(this);`.

Even when class properties are stage 3, and this guide permits their use, it will be a bad idea to use them in this fashion.
