### ISSUE TITLE
MyComponent/index.js? or ALWAYS have file name reflect default export?

### ISSUE THREAD

**Issue by justin808** [airbnb/javascript#1336]
Regarding this issue: https://github.com/airbnb/javascript/issues/949

I find it difficult to work in RubyMine/Webstorm with tons of files named `index.js`:

* Have to remember to hit a `/` after typing the name and autocomplete is not great
* Search results harder to read.

I'd like to suggest the following convention:

1. Create the file as `components/MyComponent/MyComponent.js`;
2. Create an "index" file in that directory with one line:
`export { default } from `./MyComponent.js`
3. Do the import as: `import MyComponent from 'components/MyComponent';` (using the default for the directory.

I believe this may give the best of both worlds in that 

1. The files are named per the default export.
2. Easier file navigation in most editors.
3. Avoid having multiple editor tabs open that say `index.js`.
4. Still have the concise import statement for the main file in a directory.

The cost is only to add the `index.js` file in each directory with a default component.

**Comment by radixhound** [comment]
Is the only reason to have an `/index.js` because you want a MyComponent.css file along side it?

Why not 

`/components/MyComponent.js`
`/components/MyComponent.css`

vs

```
/components/MyComponent/index.js
/components/MyComponent/MyComponent.js
/components/MyComponent/MyComponent.css
```
I have found that all the `index.js` files everywhere is a horrible pattern and I also don't see the value of the extra level of nesting. (I like to navigate my project sometimes using my mouse pointer) Practically speaking, maybe some components folders will become pretty full of files, but generally at some point some logical groupings appear and those groupings 'themes' become folder names and serve provide more information about the structure as well.

In my project I don't have any .css files alongside my components though, so I haven't experienced what that would be like on a bigger project.

**Comment by radixhound** [comment]
If you have logical groupings you can use `index.js` files for those

```
/components
   /navigation
     - index.js
     - Navbar.jsx
     - NavButton.jsx
```

and you can do an import like `import { Navbar } from 'components/navigation'`

**Comment by ljharb** [comment]
It sounds like the usability of your IDE is subpar, and you want this style guide to change to reflect that. Have you filed this upstream with RubyMine/Webstorm?

The choice of index.js is very intentional, because of the path resolution that node does with require. It will not change in this guide.

**Comment by prigara** [comment]
For those who will bump into this issue in the future: this pattern works fine in IntelliJ-based IDEs.
`import boo from 'foo'`
will resolve into foo/index.js if there's such file.

**Comment by ljharb** [comment]
@justin808 If you end up filing an upstream issue on Webstorm or Rubymine, please link it here!

**Comment by justin808** [comment]
Here's the tracking issue:
https://youtrack.jetbrains.com/issue/WEB-25886#u=1489412510633

**Comment by radixhound** [comment]
FWIW I removed my comments because I had the context of the issue wrong methinks.
