### ISSUE TITLE
some codes needs enhancement!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [airbnb/javascript#1337]
old 

```jsx
// bad
function SFC({ foo, bar, children }) {
  return <div>{foo}{bar}{children}</div>;
}
SFC.propTypes = {
  foo: PropTypes.number.isRequired,
  bar: PropTypes.string,
  children: PropTypes.node,
};

// not too good
function SFC({ foo, bar }) {
  return <div>{foo}{bar}</div>;
}
SFC.propTypes = {
  foo: PropTypes.number.isRequired,
  bar: PropTypes.string,
  children: PropTypes.node,
};
SFC.defaultProps = {
  bar: '',
  children: null,
};
```

new 

```jsx
// bad
function SFC({ foo, bar, children }) {
    return <div>{foo}{bar}{children}</div>;
}
SFC.propTypes = {
    foo: PropTypes.number.isRequired,
    bar: PropTypes.string,
    children: PropTypes.node,
};

// good
function SFC({ foo, bar, children }) {
    return <div>{foo}{bar}{children}</div>;
}
SFC.propTypes = {
    foo: PropTypes.number.isRequired,
    bar: PropTypes.string,
    children: PropTypes.node,
};
SFC.defaultProps = {
    bar: '',
    children: null,
};
```

**Comment by xgqfrms-GitHub** [comment]
# one more !


```jsx

// bad
React.createClass({
    _onClickSubmit() {
        // do stuff
    },
    // other stuff
});

// not too good
class extends React.Component {
    onClickSubmit() {
        // do stuff
    }
    // other stuff
}

``` 

## it solud be like this, 

```jsx

// bad
React.createClass({
    _onClickSubmit() {
        // do stuff
    },
    // other stuff
});

// good
React.createClass({
    onClickSubmit() {
        // do stuff
    },
    // other stuff
});

``` 

## or this.

```jsx

// bad
class extends React.Component {
    _onClickSubmit() {
        // do stuff
    },
    // other stuff
};

// very good & ES6
class extends React.Component {
    onClickSubmit() {
        // do stuff
    }
    // other stuff
}

```

**Comment by ljharb** [comment]
I'm confused - in your latter example, you seem to be referring to the "Do not use underscore prefix for internal methods of a React component." section of https://github.com/airbnb/javascript/tree/master/react - where `React.createClass` is a bad example (as it always is; it's deprecated) and an ES6 class-based component is a good example. Instead providing long amounts of code in an issue, could you either submit a pull request (so we can see diifs), or in the issue, talk only about the specific changes?

I do see what you mean in the first example; please feel free to submit a PR to fix that.

(I've also updated your comments to remove the unnecessary markdown headings (`#`), since large bold text adds noise and makes things harder to read)

**Comment by xgqfrms-GitHub** [comment]
1. ` SFC({ foo, bar, children })` !== ` SFC({ foo, bar, children })`

2. `class extends React.Component ` !== `React.createClass`

what's  I mean is that both demos should have the same condition(e.g parameters) for compare!
