### ISSUE TITLE
Discussion: Disallow global `isFinite`

### ISSUE THREAD

**Issue by amilajack** [airbnb/javascript#1347]
The global `isFinite` function casts the value passed to it and evaluates arbitrary values as finite. What are thoughts on disabling the global `isFinite` in favor of `Number.isFinite`

**Comment by ljharb** [comment]
That seems like a great idea; want to PR it into `no-restricted-properties` and add a note in the guide? (it'll be semver-major, so it might sit a bit before being merged)

**Comment by minbelapps** [comment]
Global isFinite is not the same as Number.isFinite. 
Se documentation:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite

so @amilajack  and @ljharb , why did you disable global isFinite in favor of Number.isFinite as they are not the same functions? And actually they acts very different.

**Comment by ljharb** [comment]
@minbelapps they’re the same with number types, and you should only ever be checking the finiteness of numbers.

In other words, the only way they’re not the same is if you’re relying on implicit type coercion, which is a bad practice and disallowed by this guide.

**Comment by minbelapps** [comment]
Why? I have a string, I want to check if it's valid number, so instead of
one operation I need to do several? It's not the valid way.

so easy way:

*return isFinte(someValue) ? Number.parseInt(someValue, 10): someValue;*

longWay:

*const parseResult = Number.parseInt(someValue, 10);*
*return Number.isNaN( parseResult) ? someValue: parseResult; *

I don't see where the second long way is better then the first one.

2018-05-08 20:11 GMT+03:00 Jordan Harband <notifications@github.com>:

**Comment by ljharb** [comment]
The easy way is rarely the best way. If you’re doing multiple things - converting to a number + checking something about the number - you should do it in multiple steps. Explicit is better than implicit.

**Comment by minbelapps** [comment]
so that's the case I need global *isFinite*. I will disable the eslint for
that line.

Regards.
M.B.

2018-05-08 20:52 GMT+03:00 Jordan Harband <notifications@github.com>:

**Comment by ljharb** [comment]
No, you need to do `Number.isFinite(Number(x))`, but of course you’re welcome to override whatever rules you like.

**Comment by minbelapps** [comment]
return  Number.isFinite(Number(x)) ? Number.paraseInt(x, 10) : x; // I
don't like this. Why to use 2 operations when exists one joined operation?

rerun isFinite(x) ? Number.paraseInt(x, 10) : x;  //more readable.




2018-05-08 20:57 GMT+03:00 Jordan Harband <notifications@github.com>:

**Comment by ljharb** [comment]
If you’re doing 2 operations, it’s more readable to do it in 2 separate steps.

In your case, I’d do `const num = parseInt(x, 10);` first, and then do your checking operations on `num`.

**Comment by minbelapps** [comment]
But why? Why do we need to split one working operation into 2? Or we are
planning that 2 operations to split into 20 smaller operations in the
future? I have no evidence, why it's bad. One operation I need to split
into 2.

What I understand, that 90% users use global isFinite in wrong manner, but
it doesn't mean that global isFinite is absolutely wrong and we need add
restrictions to it.

2018-05-08 21:17 GMT+03:00 Jordan Harband <notifications@github.com>:

**Comment by ljharb** [comment]
Yes, it definitely means that. If something is easily misused, it is *harmful* and should always be avoided.

**Comment by ljharb** [comment]
The documentation is irrelevant; what it does is surprising to most. I disagree with you that the isFinite example is more readable or that it has less space for errors - i find it less readable, and *more* complex because isFinite is doing 2 things at once.

**Comment by minbelapps** [comment]
For example with date time operations moment library is introduced and many
of users are very happy as there are simple short functions doing several
operations at once. The same in real life. If you giving a command for some
one "go to he shop and buy some milk", in 99.99% cases you not say "go to
that shop, if the it will be closed, go to another one, and if there will
be two shops close to you, so you can go to any one". It's because it's
enough to say "go to shop and buy a milk". Because you no that person is
capable to do this. And this person in code is global function isFinite,
quite smart to handle values in string format.  If there is a special case,
special code would be written for that case.

2018-05-09 18:30 GMT+03:00 Jordan Harband <notifications@github.com>:

**Comment by ljharb** [comment]
You're welcome to your opinion, but the reason `Number.isFinite` was added to the language is so that nobody ever has to use the global one again, for the reasons I've indicated.

**Comment by minbelapps** [comment]
One is strict, the other is not.  I don't see here any reasons to force
users.

Also,
- Number.isFinite
- Number.parseInt
 are not supported for example by Internet Explorer.
So you are forcing to use things not supported by all common browsers?

https://github.com/google/blockly/issues/571
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt



2018-05-10 2:52 GMT+03:00 Jordan Harband <notifications@github.com>:

**Comment by ljharb** [comment]
The reason is because this is a style guide, and the entire point of it is, among others, to force stricter and more explicit forms.

Separately, there’s a note at the top of the guide that you are expected to be using babel-preset-airbnb and airbnb-browser-shims, or the equivalents.
