### ISSUE TITLE
I'm not sure if this is just my lack of knowledge, but 8.3 code doesn't work.

### ISSUE THREAD

**Issue by benjaminr177** [airbnb/javascript#1397]
I get an error when I run: 
```
['get', 'post', 'put'].map(httpMethod => (
  Object.prototype.hasOwnProperty.call(
    httpMagicObjectWithAVeryLongName,
    httpMethod,
  )
));
```

With this error: 'Uncaught SyntaxError: Unexpected token )'

**Comment by ljharb** [comment]
Are you using https://npmjs.com/babel-preset-airbnb ? (Specifically, are you transforming trailing function commas?)

**Comment by ljharb** [comment]
That's because you're not putting a semicolon after line 1, and ASI is treating your array as indexing into the value `babelPresetAirbnb`. Please use semicolons.

Separately, you'd need babel-preset-airbnb to be used by the babel config that's transpiling your code on disk; you can't simply require it in runkit and have it do anything.
