### ISSUE TITLE
Question: New Release

### ISSUE THREAD

**Issue by KerenChandran** [airbnb/javascript#1410]
Is it possible for you guys to cut a new release soon? Some of us using your package for eslint (which is amazing) would like to take advantage of the updated eslint-plugin-jsx-a11y.

**Comment by cycomachead** [comment]
Was just going to file this.

FWIW, there seem to be incompatibilities with upgrading to v5. The airbnb config includes defaults that are not considered valid elements (i.e. Specifying `['']` as a list of elements to check on some rules.)

I could make a PR if that'd be helpful?

**Comment by ljharb** [comment]
@cycomachead Hmm, a PR might help explain what you mean. Certainly I don't want `[]` to override defaults, and that's a mistake I may have indeed made when upgrading; I'm not sure when `['']` appears.

**Comment by ljharb** [comment]
@KerenChandran I'm waiting on some bugfixes in eslint-plugin-react before releasing.

**Comment by cycomachead** [comment]
@ljharb When I upgraded to v5 along with the latest airbnb I saw errors for "invalid rules"
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js#L12 was one. The jsx-a11y docs suggest that you could simply have the value be "error", without the additional configuration for the same affects. There were a few others, like a label rule, that said specifying "label" as a element to check was an error because it was included in the default spec. 

I modified the a11y config to match the docs, and resolved the errors and that worked for me a couple days ago. However, I've just spent the last 30 minutes messing with my local configuration with a bunch of different versions and I can't get it into a happy state with the configuration I have right now, so I'll have to explore later on.

**Comment by ljharb** [comment]
Hm, that line certainly was meant to be an empty array.

Our rules intentionally document all options, including replicating defaults. If you find a place where that's not the case, please do make a PR to correct it.

Separately, if you find a place in `eslint-plugin-import` where providing the default explicitly errors, please file it there, because that's a bug in the plugin.

**Comment by cycomachead** [comment]
Ugh, sorry. :(

I reset all the peer dependencies to the specified versions w/ 14.1 and then loaded up jsx-a11y v5 and everything worked. Not sure what was broken before, but it seems that v5 should be an easy update. 👍

**Comment by fidelisrafael** [comment]
Hi there! I really dont know if this is a new thing, but `eslint 4.0.0.beta` has a `JSON schema` validator and [this kind of configuration](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js#L6) is not valid...Are you guys planning a new release supporting `eslint 4.0.0`?

**Comment by ljharb** [comment]
This issue actually can be closed, as v15 of the main config was released.

@fidelisrafael we will not be supporting a beta version of eslint; however, that should be fixed to `parserOptions` anyways.

**Comment by Stubbs** [comment]
Any chance you could do a quick 15.0.2 release to include this last fix?

**Comment by ljharb** [comment]
@Stubbs yes, one will be coming in the next few days.

**Comment by FredyC** [comment]
@ljharb Any info where this got stuck actually? Is 15.0.2 coming out soon, please?

**Comment by ljharb** [comment]
Sorry for the delay. v15.0.2 is released.
