### ISSUE TITLE
(comma-dangle) is a false positive in a arrow function predicate

### ISSUE THREAD

**Issue by ddaza** [airbnb/javascript#1461]
The line in the filter is an example and actual implementations might vary.

This produces an error in the line (max-len) which is reasonable
```js
const fruits = ['apples', 'oranges', 'bananas', 'pears']
  .filter(veryLongFruitVariableNameForExample => veryLongFruitVariableNameForExample === 'oranges' ||  veryLongFruitVariableNameForExample === 'pears'  );  // Error (max-len) here
```
This produces a (coma-dangle) in the multiline conditional which is wrong.
```js
const fruits = ['apples', 'oranges', 'bananas', 'pears']
  .filter(veryLongFruitVariableNameForExample => veryLongFruitVariableNameForExample === 'oranges' ||  
   veryLongFruitVariableNameForExample === 'pears'  // <---- coma-dangle error here
);
```

**Comment by ljharb** [comment]
Indeed, it's correct - comma-dangle in our config requires trailing commas on function arguments (which is part of ES2017, and transpired by babel-preset-airbnb).

In this case, "pears" ends the function that's passed to filter; since the closing invocation paren isn't on the same line as the opening one, all args should be on their own line (in this case, your long arrow function needs to be on a line by itself, with a trailing comma).
