### ISSUE TITLE
Why does eslint-config-airbnb-base set env:node?

### ISSUE THREAD

**Issue by adityavohra7** [airbnb/javascript#1476]
Pardon me if this has been discussed already (couldn't find much). 

Building on [this issue](https://github.com/airbnb/javascript/issues/1002#issuecomment-238062892), should eslint-config-airbnb-base be [setting the node environment](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/index.js#L5)? Should this also be left to apps to configure? Maybe this was done for some historical/migration reasons?

**Comment by ljharb** [comment]
I'd say that certainly, every app should configure it, whether configs are doing so or not.

The current state was not intentional; but it's also not necessarily a bug.

It seems like `rules/node` should be setting the env, but it also seems odd that you'd have to explicitly set `env: node` to `false` in your app when using our config.

**Comment by adityavohra7** [comment]
Sorry for the delayed reply! My motivation was mostly just disallowing (at lint time) any node globals in apps that run _only_ in browsers. The way things are currently set up, these globals wouldn't be caught until a later stage no?

**Comment by ljharb** [comment]
Yeah, you'd need to explicitly set the env to `node: false, browser: true` the way things are currently set up.
