### ISSUE TITLE
colocation of tests

### ISSUE THREAD

**Issue by travi** [airbnb/javascript#1485]
@ljharb sorry for hijacking https://github.com/airbnb/javascript/issues/1447 after you mentioned discouraging colocation of tests with source files, but i am legitimately curious about your reasons.

you mentioned the more obvious piece about tool compatibility, which i think eslint is the last of in my case, though i won't be surprised if i realize that i forgot about something once i try. with the breadth of tools you maintain, i'm sure you have reasons that would be worth considering if i take steps closer to colocation. 

my main motivations to move to colocation are mostly around code that changes together being packaged together. working with react has even further strengthened this thought process for me since packaging all parts of a component together provides so many benefits. in addition, dropping the need to navigate up and back down a deeply nested directory structure for every source import from a test. would certainly be nice as well.

**Comment by ljharb** [comment]
So, the primary concern, which overrides all others, is "not every tool works with glob-based configuration". babel still doesn't, for example - eslint only added this in v4 (prior to v4, since not linting a project is wildly irresponsible, having colocated tests means you had to litter your codebase with eslintrc files). This also applies to virtually every other unix tool - very very few have glob-based configuration. If your toolchain fully supports it, great! While it's still pretty likely that you'll run into tools that don't work well with it, at least that unblocks you to consider additional concerns.

1. If you want code packaged together, *package it*.
1. If you don't like lots of `../`, then that's more motivation to extract code into separate packages.

(Regarding approaches people tend to use, whether just in tests or also in production code, to avoid lots of `../`, please see my comment [here](https://github.com/AlexTes/javascript-best-practice/issues/1#issuecomment-303502935))

It's very important to be able to keep tests and code separate - when shipping to production, when applying static analysis tools, when making large-scale refactors of test-only code, etc - all these things *can* be done with colocated tests, but imo not quite as well.

**Comment by travi** [comment]
thanks for sharing your thoughts here. i always like to consider perspectives of people with more/different experiences, so your thoughts are valuable.

> 1. If you want code packaged together, package it.
> 2. If you don't like lots of ../, then that's more motivation to extract code into separate packages.

agreed on these being smells and motivators to extract. sometimes extraction is more practical than others, but this is one of the ways i attempt to address the issue. i have considered most of the approaches to avoiding `../` that you mentioned as well as the discouraged (and i think no longer supported?) use of `$NODE_PATH` and have landed on dealing with the `../` being the least bad option short of colocation of tests or extracting to make a project smaller.

since my code gets bundled based on following the import tree using webpack and rollup, separating production code isn't really an issue for me and i do consider tests a form of source code. 

i think i'll still give colocation a try with eslint v4, but this helps me keep an eye out for more things that could be problems.
