### ISSUE TITLE
New rules suggestion to prevent common coding typos (length and constructor)

### ISSUE THREAD

**Issue by yvele** [airbnb/javascript#1492]
As a non native english developper I lost a huge amount of time fixing the same typos again and again.

I fixed common **`constructor`** typos using [id-blacklist](http://eslint.org/docs/rules/id-blacklist) rule. It's safe because who would ever use those IDs:

```js
{
  "id-blacklist" : ["error",
    "contructor",
    "contrutor",
    "construtor",
    "construcor",
    "constuctor"
  ]
}
```

I also fixed **`length`** typos using [no-restricted-properties](http://eslint.org/docs/rules/no-restricted-properties), It's safe because what evil mind would ever use `lenght` in any code?!

```js
{
  "no-restricted-properties" : ["error", {
    property : "lenght"
  }]
}
```
Could we have this directly within [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base)?

This could save the world a huge amount of time 😉 

Related issue: https://github.com/eslint/eslint/issues/8940

PS: I'm pretty sure there is many other use cases, for example this related issue about `propTypes` typos: https://github.com/yannickcr/eslint-plugin-react/issues/65 (and see also [react/no-typos](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md))

**Comment by ljharb** [comment]
The concern is that this would require a lot of configuration - all the possibly typos of "length", for example, would be a long list.

The `constructor` property should never be used; are you referring to the `class` method?

(The `no-typos` rule hasn't yet been released; we'll try it out on Airbnb's codebase and see if it's viable to enable it by default once it is)

This seems like it'd be more appropriate as a custom rule that detected typos based on a list of commonly misspelled things - ie, you'd configure it with "length" and "constructor", and it'd look for things that were "close" to them. I don't think it's really scalable to start accumulating spelling mistakes in our config.

**Comment by yvele** [comment]
I don't think we should add an exhaustive list of all typos we can think of, but at least only manage the most common typos developers are going crazy with

I'm mostly thinking about
 - `length` misspelled as `lenght`
 - `constructor` misspelled as `contructor` or `constuctor`

I know that this is pretty "organic" and only based on experience, but we could save precious time to many developers with only those 2 rules

----

About `constructor`, I'm referring to the real `class` `constructor`, using [id-blacklist](http://eslint.org/docs/rules/id-blacklist) is kind of a "semantic" hack as this:

```js
class Foo {
  constructor() { ... }
}
```

is considered as a real `constructor` by eslint, and this

```js
class Foo {
  constXuctor() { ... }
}
```

is considered as a `class` method, and then can be banned

**Comment by ljharb** [comment]
The problem, as you've identified, is that that's highly subjective - neither of those are things I commonly misspell, nor see commonly misspelled in codebases I work on. That of course doesn't mean they're not problems! but it does mean that "common" isn't really something that can be claimed.

For `constructor` - it's not really a problem for subclasses, since you have to call `super` and you can't call that outside the constructor - it's mainly a problem for base classes. At Airbnb, the only `class`es we tend to use are React components, and we avoid inheritance, and prefer composition to reuse code, so it's not something we tend to run into. In general, I'd say a general rule that handles `class` constructors specifically might be a better thing to add to eslint.

`no-restricted-properties` is already a long list for us; I'd like to avoid it growing too quickly, and `id-blacklist` is definitely hacky :-)

**Comment by yvele** [comment]
Instructive discussion.. it's maybe more a problem for non native english developers (I'm french).

We also use a lot of classes on non react projects.

We will keep those rules added to our own rules (inherited from airbnb).

I agree eslint-config-airbnb-base should be kept as simple as possible

Feel free to close the issue, and thanks again for your time 😉

**Comment by ljharb** [comment]
Non-English speakers are important too!

I do think that it's not something we should add; but I'd love to see a core no-typos rule.
