### ISSUE TITLE
What will AirBnb do with Facebook adding a new clause to it's BSD license?

### ISSUE THREAD

**Issue by sabapk** [airbnb/javascript#1534]
AirBnb has been widely using React since 2014 and contributing to the open source.
As per the latest clause added by FB in the BSD license to use React, any organisation cannot file a patent application for their product in future. If they do, the license will be revoked and the product will have an unlicensed software in it, which will be illegal.
This has triggered a lot of discussions after Apache Foundation disallowed applications using Facebook libraries. After developers reaching to Facebook, the giant is still firm on it's decision.
How is AirBnb Engineering taking this decision? Are they moving to another JS Framework?

**Comment by ljharb** [comment]
This is not a new clause at all; it's been part of React's license for many years. ASF's decision is confusingly recent, after the rest of the industry had already long since made their decision about it.

Airbnb has always been content to use React with its current license, and will continue to do so for the forseeable future.

**Comment by ljharb** [comment]
I'm pre-emptively locking this thread, since I'm not a lawyer, and there's nothing productive I expect from this discussion. Please feel free to email me privately if anyone has further questions or comments.
