### ISSUE TITLE
ReadMe should mention that using this styleguide and its eslint plugins effectively requires babel

### ISSUE THREAD

**Issue by williscool** [airbnb/javascript#1544]
Requires babel and a preset that compiles es6 code for use in node projects. 

Due to the import syntax not yet being supported in current (circa creating this ticket) versions of node.

https://github.com/nodejs/help/issues/53#issuecomment-280899509

https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c

**Comment by ljharb** [comment]
That's a good idea.

We certainly expect you're using https://npmjs.com/babel-preset-airbnb and https://npmjs.com/airbnb-browser-shims, or the equivalent. I'll add a note to the readme about it.

**Comment by jondkinney** [comment]
@ljharb thanks for adding the clarifying note in the readme. However, it seems a bit needlessly overly opinionated? Perhaps that's the whole point of the guide :) But would it be fair to say that you can still use the airbnb styleguide with a non-ejected [CRA](https://github.com/facebook/create-react-app) application that is using the default `babel-preset-react-app` instead of what you specifically mention: `babel-preset-airbnb`? 

There are countless blog posts that discuss how to setup eslint and prettier with airbnb styleguide and none of them talk about the need to eject from CRA and ensure that your babel config is using the airbnb preset instead of the one provided by CRA. 

Can you please clarify if there will be any issues or edge cases setting up eslint and prettier to use the airbnb config while sticking in the confines of a non-ejected CRA app? The only thing that comes to mind is that is could be possible (if I'm thinking about this right) to have eslint suggest changing a line of code to something that the `babel-preset-react-app` config won't properly transpile, leading you to need to override the eslint config or ignore a rule conditionally in a file or on a line. Have you seen that in practice? Is it worth worrying about? Thanks!

**Comment by ljharb** [comment]
I don't believe CRA can be used with airbnb linting/babel settings without ejecting; and no, I would not assume that any other babel preset will be completely compatible.

Internally, we always require CRA apps to be immediately ejected, so that they can utilize airbnb's settings
