### ISSUE TITLE
React/JSX-curly-brace-presence is too strict

### ISSUE THREAD

**Issue by kripod** [airbnb/javascript#1656]
In the case below:

```jsx
<div css={`
  background: #009688;
  transition: background 0.5s;
`}>
  Hello world!
</div>
```

The linter throws an error for using curly braces, but it's impossible to have multi-line parameters without them, as the template literal notation (``string``) requires curly braces to be used.

`eslint --fix` produces the following result:

```jsx
<div css="
  background: #009688;
  transition: background 0.5s;
">
  Hello world!
</div>
```

**Comment by ljharb** [comment]
That definitely seems like a bug in `eslint-plugin-react` - can you file it there? (although I think https://github.com/yannickcr/eslint-plugin-react/pull/1458 fixed it in v7.5.0+; what version are you using?)

(separately, `css` is an invalid parameter for a `div`, so that example is a bit confusing)

**Comment by kripod** [comment]
I'm using eslint-plugin-react v7.5.1, and the `css` prop is being transformed by babel-plugin-emotion.

**Comment by ljharb** [comment]
In that case, please do file a new issue on the plugin repo :-) Thanks!

**Comment by kripod** [comment]
@ljharb Fantastic, thank you for your kind assistance! 😊

**Comment by ljharb** [comment]
(linking to https://github.com/yannickcr/eslint-plugin-react/issues/1592)
