### ISSUE TITLE
Chaining example for #26.2: Cache jQuery lookups

### ISSUE THREAD

**Issue by keith24** [airbnb/javascript#1666]
> [26.2](https://github.com/airbnb/javascript#jquery--cache) Cache jQuery lookups.
> 
> ```javascript
> // bad
> function setSidebar() {
>   $('.sidebar').hide();
> 
>   // ...
> 
>   $('.sidebar').css({
>     'background-color': 'pink',
>   });
> }
> 
> // good
> function setSidebar() {
>   const $sidebar = $('.sidebar');
>   $sidebar.hide();
> 
>   // ...
> 
>   $sidebar.css({
>     'background-color': 'pink',
>   });
> }
> ```

But how about: 

```javascript
// best
function setSidebar() {
  $('.sidebar').hide().css({
    'background-color': 'pink',
  });
}
````

I *assume* it's fastest because it doesn't perform two jQ lookups and doesn't declare a new const to memory.  However, I didn't go to school for CS and I don't know much about JS under the hood.  

I also find chains easy to read since long ones can be split across lines in compliance with [19.6](https://github.com/airbnb/javascript#whitespace--chains).

**Comment by ljharb** [comment]
The "good" is faster than the "bad" solely because it doesn't have to crawl the DOM twice.

Your "best" example isn't generically better than the "good" one, because the `// ...` code might need to happen between the `hide` and the `css` calls. This isn't about "chains vs not chains" - the examples simply aren't chainable, because of the intervening code.

**Comment by keith24** [comment]
OK, makes sense.
