### ISSUE TITLE
Rules should assume strict mode

### ISSUE THREAD

**Issue by erights** [airbnb/javascript#1671]
Rules 
https://github.com/airbnb/javascript#functions--in-blocks
https://github.com/airbnb/javascript#functions--note-on-blocks
https://github.com/airbnb/javascript#functions--arguments-shadow
only make sense for sloppy code, which therefore necessarily already violates the style guide by being sloppy.

**Comment by erights** [comment]
https://github.com/airbnb/javascript#functions--declarations
either assumes sloppy, or it does not make sense, depending on what it means by "hoist". In strict mode, both the named function declaration and the const declaration hoist the scope of the declared variable name in the same way. The difference is only that the function form is also dynamically initialized.

For example, mutual recursion can be written either way, though the text suggests that it would not, and should not, work for the const form.

**Comment by erights** [comment]
Regarding the confusion of function hoisting, how about recommending that function declarations should be written where they hoist to, the top of their block. This avoids misleading readers.

**Comment by ljharb** [comment]
The sloppy code notes you've mentioned may only make sense in sloppy mode, but it is a simpler rule to remember to simply never do it, even in strict code - that avoids the refactoring hazard of code being copy-pasted into sloppy mode, or moved into another file that may not be using `import`/`export`, or the strict pragma.

Due to the arcane specifics of how the TDZ works, you're correct about hoisting and mutual recursion. In practice, however, we find recursion is best avoided entirely, and the way it's written is easier for devs to understand and remember.

Re the latter point, by writing a function declaration, a refactoring hazard exists where one could later add code that relies on hoisting - so the only safe choice is to never use a function declaration.

**Comment by erights** [comment]
> avoids the refactoring hazard of code being copy-pasted into sloppy mode

Hurting strict code practice to accommodate sloppy mode is madness.

**Comment by ljharb** [comment]
All of this advice increases readability in strict code too, even if the hazards no longer exist.

**Comment by erights** [comment]
> All of this advice increases readability in strict code too, even if the hazards no longer exist.

Not true for
https://github.com/airbnb/javascript#functions--in-blocks
https://github.com/airbnb/javascript#functions--note-on-blocks
https://github.com/airbnb/javascript#functions--declarations

Does not even make sense for
https://github.com/airbnb/javascript#functions--arguments-shadow
since it is impossible in strict code anyway.

**Comment by ljharb** [comment]
I’m arguing that it is true; eg, defining functions in blocks is more confusing for me, and avoiding them produces clearer code.

Regardless, the reality is that there is much code that is non-strict and will forever be; it’s important that this guide is a balance of assuming best practices and accepting reality.
