### ISSUE TITLE
Why use avoidQuotes in object-shorthand?

### ISSUE THREAD

**Issue by BinotaLIU** [airbnb/javascript#1816]
```javascript
{
  'x.y'() {}
}
```

Above code would be invalid, have to change to 
```javascript
{
  'x.y': function () {}
}
```

Seriosly I have no idea why we have to do this.
  
The guide said:
https://github.com/airbnb/javascript/blob/2ba36de952fcb6a931471980f4fbbdc4df468baa/README.md#L195-L215

When we need to use `avoidQuotes`?
I read the change history of the eslint config, found following:
https://github.com/airbnb/javascript/commit/10f4dd88aaab6a8456373a3a0c5fc00ada3c4172

What does the "consise form" mean in the commit message?

**Comment by olstenlarck** [comment]
I'm agree with that rule. It's a lot more clear and correct. Your first example is a bigger mess for my eyes than the second one, definitely.

As about the referenced example, at least - it is shorter and not using anonymous function. I even love that, and actually in my config which is on top of AirBnB's, i'm forcing always to use arrow functions, unless you need `this` in which case you are also forced to name the function - no anonymous functions.

**Comment by ljharb** [comment]
"concise form" means when you're using concise object methods - like `{ foo() {} }` You can read about the avoidQuotes option [here](https://eslint.org/docs/rules/object-shorthand#avoidquotes).

The reason we have it configured this way is because it makes the most sense for us to only use the concise form with identifiers - ie, with unquoted names.
