### ISSUE TITLE
What's the general consensus for nested destructuring assignment?

### ISSUE THREAD

**Issue by Li357** [airbnb/javascript#1840]
I wanted to know if there's some general consensus on whether or not it's okay to use nested destructuring assignment:

```javascript
const obj = { a: { b: 'foo' } }; // obj.a.b = 'foo'
const { a: { b } } = obj; // b = 'foo'
```

Is this something discouraged? Currently, I refrain from it because it looks messy and a bit unreadable, but is there an opinion from airbnb?

**Comment by ljharb** [comment]
We don't have any sort of internal consensus - which means it's an individual judgement call. I'd say that the benefits of destructuring, nested or otherwise, are primarily that you don't have to repeat the property name. If nested destructuring can provide that without sacrificing readability, then it seems great.

**Comment by ericblade** [comment]
I had avoided doing this because I thought (without verifying first) it would pollute the variable namespace with 'a', but I just actually tested it, and it does not.  FWIW, in case anyone else might've thought that.
