### ISSUE TITLE
why should not use getters/setters?

### ISSUE THREAD

**Issue by frontEndNewComer** [airbnb/javascript#1880]
I'm so confused with "24.2 Do not use JavaScript getters/setters as they cause unexpected side effects and are harder to test, maintain, and reason about. "

Getters/setters, as we all know, is a standard way in ES6, but why you guys say "do not use"?
What are the side effects? 
What are we worrying about?

Can we support more descriptions about it ?

**Comment by ljharb** [comment]
So so many reasons. One of the least important is performance - they're massively slow.

The most important is because it reduces clarity and maintainability, all for the insignificant benefit of avoiding `()` or `(x)`.

Getters and setters are "standard" but so is "with" and "eval" - "in the spec" is never a sufficient justification to use something.

**Comment by yvele** [comment]
Related to https://github.com/airbnb/javascript/issues/269

**Comment by ljharb** [comment]
Also #757, #1367, #670.

**Comment by mariovelickovski** [comment]
aa

**Comment by mariovelickovski** [comment]
👍

**Comment by mariovelickovski** [comment]
👍

**Comment by frontEndNewComer** [comment]
Thank you,plz close the issue :)

**Comment by Raiondesu** [comment]
@ljharb, I have some comments about your arguments:

> One of the least important is performance - they're massively slow.

Only for plain JS objects. For ES6 classes the difference is negligible. [Proof](https://jsperf.com/accessors-vs-functions/1). So why ban them everywhere?

Even if "for consistency" - why even use computed gets/sets (in any form) on a plain object? The approach to writing plain functional objects is usually drastically different from classes' anyway.

> The most important is because it reduces clarity and maintainability

Any explanation on this? Couldn't find any concrete or up-to-date arguments anywhere on the web. Refactoring difficulty is the same, since all refactoring tools in IDEs treat getters and setters as functions.

Clarity, in this particular case, depends on the point of view. It's obvious for me that getters or setters should not be used for heavy computational tasks.
Computing a full user's name is fine. So why ban this?

Getters and setters are **intended** to hide computational functionality. They are made *specifically* so you wouldn't know if the value is computed. This is **the point**.
So the end-user of a library does not have to explicitly know, which value is computed and which isn't.

If this is the actual reason for a full ban on getters and setters - then why not state is as such? Some reasoning is always better than no reasoning.

> all for the insignificant benefit of avoiding `()` or `(x)`.

This is not the benefit. This is taste. Just as your personal dislike for getters and setters. This should be understandable. So, minding this, how come your taste is more valid than others' taste? This is *very* far from "a mostly reasonable approach". Style guides are made to break people's tastes in benefit of a uniformal approach to writing code.

The benefit is in freeing the end-user of cognitive load about what is computed and what is not. When an operation takes O(n) - it does no reall difference when its result is saved into a variable or returned from a function. Hence, there's no matter if the property is computed or not.

So, keeping everything of what I wrote in mind, I'd re-formulate the end-reason for at least a partial getters/setters ban as following:

---
Do not use JavaScript getters/setters in plain javascript object. Only usages in classes are allowed.

> Why? Getters and setters obscure value computations form the end-user and are up to [30 times slower](https://jsperf.com/accessors-vs-functions/1) when used in plain JS objects.
---

**Comment by ljharb** [comment]
@Raiondesu i'm afraid a microbenchmark like jsperf isn't "proof" of anything; you'd need to run your actual code in your actual application to determine if the performance matters.

You shouldn't *be* hiding computation - properties should be properties, and functions should be functions. Deviating from that harms clarity and maintainability.

We will not be permitting getters and setters in classes, but you're welcome to fork the guide and make whatever changes you see fit!

**Comment by Raiondesu** [comment]
> You shouldn't be hiding computation - properties should be properties, and functions should be functions. 

Refusing to hide computation goes against enapsulation.

> Deviating from that harms clarity and maintainability.

Again, what are those giant unholy maintainability costs you're talking about?

I could only find sources arguing that getter and setter methods are [**much harder** to maintain](https://www.javaworld.com/article/2073723/why-getter-and-setter-methods-are-evil.html) (also [this](https://www.yegor256.com/2019/03/12/data-and-maintainability.html) and [this](https://coderanch.com/t/627819/java/encapsulation-improve-maintainability) and [this](https://techblog.bozho.net/getters-and-setters-are-not-evil/)).

---

After all, I'm not saying that you have to permit the usage of getters and setters in your guide. It's **your** guide, after all.

I'm saying that the reasoning in the guide is not on pair with your arguments. And this is a lot of problem for a single entry in the most referenced JS style guide in the web. And a lot of responsibility.

Should we consider fixing the reasoning then?

**Comment by ljharb** [comment]
Encapsulation is about hiding implementation details, but "there are effects" is not an implementation detail - it's part of the public API. Additionally, since you can reflect to determine if something is a getter, *encapsulation here is not possible*.

I find the reasoning correct as-is.

**Comment by ktiedt** [comment]
> I find the reasoning correct as-is.

None of those reasons, which would help explain what `they cause unexpected side effects and are harder to test, maintain, and reason about` actually means... are listed in the guide though... where is the harm in making the explanation in the guide as clear as possible?

I see zero examples of unintended side effects, they are no different to test than any other JS which makes them just as simple to maintain... 

Please cite cases for these `they cause unexpected side effects and are harder to test, maintain, and reason about` so their is something to understand the justification for this setting.

**Comment by waruyama** [comment]
>> One of the least important is performance - they're massively slow.

> Only for plain JS objects. For ES6 classes the difference is negligible. 

I just had to improve performance of a rendering library which had a massive number (millions) of calls to one single getter of a very simple class. Changing this getter to a function gave an overall 3% performance improvement to the library, which is quite impressive for such a minor change. It seems that the performance difference is only negligible if the number of calls are not too high.

**Comment by host510** [comment]
I understand time elapsed since the discussion, but I wonder whether this is good to use getters setters in the first place. If you try to access a variable by name, and the variable doesn't exist, first of all JS will try to find it in the prototype chain, and after that will execute getter. Am I right?

**Comment by ljharb** [comment]
@host510 no, that's not correct. "getters" are an object property thing, not a variables thing. If you try to access a *property* on an object, it will look for it on the current object, and if missing, will look up the prototype chain one at a time until it finds it. When it finds it, if it's an accessor property, it invokes the getter.

No, it's not good to use getters/setters in the first place, which is summarized in the issue above.

**Comment by Raiondesu** [comment]
> which is summarized in the issue above
Which is not summarized anywhere in this issue (nor in the guide) yet, and people here spent a good deal of effort to get the proper explanation from @ljharb.
This explanation is still not present at the moment (and I don't consider "harder to reason about" as any explanation whatsoever).

**Comment by ljharb** [comment]
> None of those reasons, which would help explain what they cause unexpected side effects and are harder to test, maintain, and reason about actually means... are listed in the guide though... where is the harm in making the explanation in the guide as clear as possible?
>
> I see zero examples of unintended side effects, they are no different to test than any other JS which makes them just as simple to maintain...
>
> Please cite cases for these they cause unexpected side effects and are harder to test, maintain, and reason about so their is something to understand the justification for this setting.

I don't have any concrete cases off the top of my head. However, using a getter has the benefit of "you don't have to type `()`" and has the downside of "it looks like a normal property, but it's actually a function call". In my experience, this has caused a large amount of friction when investigating bugs, and when understanding code as written.

JS isn't Ruby. If you want a property access/assignment to have special behavior, *make it a normal method*. It's not performant, idiomatic, or obvious when you use a getter/setter.

**Comment by xfg** [comment]
@ljharb I want to protect the properties of an object from outside changes, but make it possible to read the properties of the object. That is, I want to get encapsulation. Now, I solve it like this:

```javascript
class User {
  #id;
  #name;

  get id() {
    return this.#id;
  }
  get name() {
    return this.#name;
  }
  changeName(name) {
    if (name.length < 2) {
      throw new DomainException('Username can not be less then 2 characters.');
    }

    this.#name = name;
  }
}
```
How can I get the same result without getters?

**Comment by ljharb** [comment]
Using `Object.freeze()`. You can even `Object.freeze(this)` in the constructor, and then use normal public fields.

**Comment by BenceSzalai** [comment]
I like the idea of getters and setters, but came to share an issue I had with them recently which will certainly make me think twice before using them, although it was my fault in a sense to begin with, but the language did not at all helped me to avoid such an issue.

So one possible serious issue can be if the getter has a side effect. As a general consensus reading the property of an object should never change the contents of such property, object or generally speaking anything in the working memory. However once the property access may be solved by a function there is nothing to enforce this.

Right, so no one should write a getter that has side effects, fair enough. However there's nothing preventing someone from doing so either because of a mistake or because of lack of understanding regarding the possible consequences.

Sure, something like this is reasonably harmless:
```js
  get id() {
    return this.#id;
  }
```

The problem is that when someone calls `user.id` (based on the above example) they don't know if the implementation is something like this:
```js
  get id() {
    return this.#id++;
  }
```

This makes no sense obviously, but it is easy to think of getters as a place to put logic that has side effects. From than on it becomes impossible to have a consistent grasp on what really is the status of some variables and properties which are effected by the getters.

To add to the confusion when one tries to debug such code, the IDE is very much likely call those getters a bunch of times to provide value hints etc. basically sprinkling the debug session with side effects.

Wrap these in few levels of abstraction, and welcome to debugging hell, where inspecting properties changes them and depending on where and how many breakpoints you have the app behaves different.

I'm not saying this is an issue with getters. It is clearly an issue with writing a getter with side effects.

What I'm saying that there are no effective tools to prevent someone to write a getter with side effects, and the consequences can be catastrophic and extremely difficult to identify.

**Comment by ktiedt** [comment]
> I like the idea of getters and setters, but came to share an issue I had with them recently which will certainly make me think twice before using them, although it was my fault in a sense to begin with, but the language did not at all helped me to avoid such an issue.
> 
> So one possible serious issue can be if the getter has a side effect. As a general consensus reading the property of an object should never change the contents of such property, object or generally speaking anything in the working memory. However once the property access may be solved by a function there is nothing to enforce this.
> 
> Right, so no one should write a getter that has side effects, fair enough. However there's nothing preventing someone from doing so either because of a mistake or because of lack of understanding regarding the possible consequences.
> 
> Sure, something like this is reasonably harmless:
> ```js
>   get id() {
>     return this.#id;
>   }
> ```
> 
> The problem is that when someone calls `user.id` (based on the above example) they don't know if the implementation is something like this:
> ```js
>   get id() {
>     return this.#id++;
>   }
> ```
> 
> This makes no sense obviously, but it is easy to think of getters as a place to put logic that has side effects. From than on it becomes impossible to have a consistent grasp on what really is the status of some variables and properties which are effected by the getters.
> 
> To add to the confusion when one tries to debug such code, the IDE is very much likely call those getters a bunch of times to provide value hints etc. basically sprinkling the debug session with side effects.
> 
> Wrap these in few levels of abstraction, and welcome to debugging hell, where inspecting properties changes them and depending on where and how many breakpoints you have the app behaves different.
> 
> I'm not saying this is an issue with getters. It is clearly an issue with writing a getter with side effects.
> 
> What I'm saying that there are no effective tools to prevent someone to write a getter with side effects, and the consequences can be catastrophic and extremely difficult to identify.

And yet it would be better to educate people on this than to say getters are bad.

Literally no reason to over complicate this but the Airbnb folks who wrote this rule and explanation are doing just that, which ultimately leads to more long posts that also over complicate things. 

Education > unsupported opinions

**Comment by tobx** [comment]
@BenceSzalai 
> Sure, something like this is reasonably harmless:
> 
> ```js
>   get id() {
>     return this.#id;
>   }
> ```
> 
> The problem is that when someone calls `user.id` (based on the above example) they don't know if the implementation is something like this:
> 
> ```js
>   get id() {
>     return this.#id++;
>   }
> ```

Something like this must be documented somewhere. You can anyway never know what is happening in the background of a library except if you read the code. The whole idea of encapsulation is that you do not know it.

If a getter needs to do stuff in the background than it probably has a good reason for it.

Here you would have the exact same expectations (thinking that `id` is private and that this is the reason for the `getId` function):

> ```js
>   getId() {
>     return this.#id++;
>   }
> ```

And still it increments `id` in the background.

This stuff needs documentation and is not your task as a library user to anticipate by the way the library is using syntax.

`id` could also be incremented by other factors like a timer.

If a programmer is not able to program its library in a way that users understand it, then he will also not be able to do so without using getters.

**Comment by tobx** [comment]
@ljharb

> i'm afraid a microbenchmark like jsperf isn't "proof" of anything; you'd need to run your actual code in your actual application to determine if the performance matters.

First of all, if you forbid a language feature because of performance reasons, than it is on you to proof it, not the other way around.

Second, in this case comparing `getId()` and `get id()` is quite enough to proof that there will be no performance issues with JS getters compared to getter functions. That is independent of the rest of your application logic.

The fact that a JS getter is slower than a simple variable access will never be a performance issue. If a programmer codes a particle engine that requires a JS getter for each particle update, then you will probably never ever hear of that engine, because it will have too many other issues.

As I said in my post before:

> If a programmer is not able to program its library in a way that users understand it, then he will also not be able to do so without using getters.

**Comment by ljharb** [comment]
@tob you may be right, and performance is a moving target. Either way, it makes code *less clear* because you’re masking that you’re calling a function, so they should be avoided like the plague for that reason alone.

**Comment by tobx** [comment]
> @tobx you may be right, and performance is a moving target. Either way, it makes code _less clear_ because you’re masking that you’re calling a function, so they should be avoided like the plague for that reason alone.

I think the opposite is the case. For me this falls into the category "premature optimization":
https://wiki.c2.com/?PrematureOptimization

If you waste time to think about why this is a function call, then libraries should use more getters in order to give you more time to think about your own code.

Even if this is not about optimization, but about background logic, the main goal of a library is to encapsulate the logic from the user as good as possible, so that the user can use it without much thinking.

Also the code is not less clear at all, because the library code looks like `get value()`. In most cases this is way more clear than something like `value()` and at least better readable than `getValue()`. For the user of the library the code also gets more clear, because e.g. `.value` as said before, stops you from thinking about it.

If you have any issues with a library you have to look into the code anyway or contact the developer. Obviously writing a `getter` that changes state in an unexpected way is wrong, but so is: `setX(value) { y = value; }. No reason to forbid functions, because they make less clear what happens in the background, right?

**Comment by ljharb** [comment]
It's not about optimization because "function call" isn't about overhead, it's about what behavior can happen. Code is MUCH less clear when you do `x.y = z` or `x.y` and something can happen that's not "setting a property" or "getting a property". JS isn't ruby; the difference matters on a conceptual level, and that's very critical.

Using a function explicitly is fine because the user knows they can go read the implementation if they need to. There's no static indicator of that for getters.

Put another way, you're introducing indirection to your code for the *sole* advantage of writing `x.y` instead of `x.y()` or `x.y = z` instead of `x.y(z)`.

**Comment by tobx** [comment]
> It's not about optimization because "function call" isn't about overhead
I know, that's why I said "Even if this is not about optimization, but about background logic..."

> Code is MUCH less clear
It is much clearer and I explained why in my last post and I also explained why it is better to not know that there is more background logic.

> Using a function explicitly is fine because the user knows they can go read the implementation if they need to. There's no static indicator of that for getters.
Yes, but that does not matter, because you anyway should not know about background logic. As I said, it is better for you to know less about the background logic, because you should think less about background logic.

> Put another way, you're introducing indirection to your code for the sole advantage of writing x.y instead of x.y() or x.y = z instead of x.y(z).
Put another way, you simplify your interface for others.

Please give me only one valid example for a getter that leads to confusion where the reason for it is the getter and not the programmer.

**Comment by ljharb** [comment]
You should absolutely know that background logic _is happening_. That's what explicit function call syntax gives you - you don't HAVE to read it, but you know it's doing something. Basic property access and assignment having the potential for any kind of effect is what's harmful.

Either way, the position of this guide, or the best practice in the wider community, is unlikely to change, so I'm not sure what you're arguing towards.

**Comment by tobx** [comment]
> You should absolutely know that background logic _is happening_. That's what explicit function call syntax gives you - you don't HAVE to read it, but you know it's doing something. Basic property access and assignment having the potential for any kind of effect is what's harmful.

But you SHOULD not know as I explained before. It is better NOT to know. Please just give me a single real world example of why you should know it and where it would be harmful.

> Either way, the position of this guide, or the best practice in the wider community, is unlikely to change, so I'm not sure what you're arguing towards.

You do not really refer to any of my arguments anyway. You kind of just repeat what you said before. I said the third time now that it is better when you have less information and explained why. So you might be right. There is no point.

Anyway, in generally a guide should be open for change if this is in the peoples interest. Style guides of many modern languages are updated quite regularly. Also I am arguing to improve my best practices. Many times before I got convinced by others.

**Comment by ktiedt** [comment]
@tobx  they haven't found a concrete example in over 4 years at this point.  It's never been about est practices or even "good" anything, this entire argument from these folks is and has been driven by only 2 things ever: 

- Personal preference 
- Ego 

🤷‍♂️

**Comment by tobx** [comment]
I just stumbled over an issue with another library that does not use getters:

`scene.isActive` is a function not a getter, but I wrote `while (scene.isActive)` instead of `while (scene.isActive())`. Even though I am using TypeScript, this is no error, because TypeScript is not strict enough to check whether the while condition returns a boolean.

`while (scene.isActive)` will always return true, so it is an infinite loop. This happened, because I did not check the API or code before using it. This could not have happened if the library would have used a getter, because using a getter as a function (the opposite case), in TypeScript it would have been an instant error and JavaScript would at least fail at runtime.

**Comment by ljharb** [comment]
Since everything doesn't use a getter, the only solution is to *check the API of something before using it*. No automated tool can free you of that obligation. (also, unit tests would catch it basically immediately).

**Comment by tobx** [comment]
> Since everything doesn't use a getter, the only solution is to _check the API of something before using it_. No automated tool can free you of that obligation. (also, unit tests would catch it basically immediately).

The main point of this discussion was that the programmer should know what is happening behind the scenes and that not using getters should make the code more clear. Now you tell me, that we should check the API before every function call? And even though you check, it can easily happen that you forget to write `()`, because sometimes it will just be a variable and sometimes a function, how would you remember that?

Also it can be extremely difficult to catch that in a unit test. A while loop might run in an background task async. It can waste memory and CPU. That is pretty difficult to spot, because it can slow down the application in completely different parts.

**Comment by ljharb** [comment]
Yes, you should always know the API of the thing you're using. It's still advantageous for the thing you're using to *look* like what it's doing, and getters don't look like what they're doing.

I do applaud you, though, as nobody has ever in my entire career attempted to make a performance argument in *favor* of getters :-)

**Comment by tobx** [comment]
Same argument applies to `while (scene.isActive)`. It does not look like what it's doing. But it would look like what it's doint if it would be a getter.

**Comment by tobx** [comment]
Also compared to your argument, it can lead to a serious bugs, that are hard to track, while your argument just leads to performance issues and like I said before, it only leads to performance issues if the programmer does not know what he is doing.

> I do applaud you, though, as nobody has ever in my entire career attempted to make a performance argument in _favor_ of getters :-)

I never made a "performance" argument in favor of getters.

**Comment by ljharb** [comment]
These kinds of issues are present with any pattern, but avoiding getters makes your code simpler, more understandable, and more performant. I’m not sure what else there is to discuss.

**Comment by tobx** [comment]
Me: Here is an example where getters make code more understandable and avoid bugs.

You: Avoiding getters makes your code more understandable.

Are you trolling now? Where is your argument?

**Comment by ljharb** [comment]
I don’t agree that your example is improved by using getters, but thanks for providing it.

**Comment by tobx** [comment]
Me: My example shows how forgetting to set ‘()’ can lead to an infinite background loop and serious, hard to track bugs. This issue would not be there if you would use getters.

You: I don’t agree that your example is improved by using getters.

Yes, that really is a strong argument now, you are trolling, right?

**Comment by ljharb** [comment]
k, at this point i’m going to hide all these comments because they’re getting trollish themselves.

**Comment by ktiedt** [comment]
To be fair Airbnb folks been trolling this thread for years now.  Just delete it if y'all refuse to listen objectively to users issues. It's been demonstrated time and time again that the documentation for this is lacking at best and wrong at worst and yet here folks are making fun of legitimate arguments that illustrates why the animosity towards getters is misplaced. 

You can't fix bad programmers with ridiculous constraints they will just find another way to be ridiculous, it's a race to the bottom. Educate, which y'all are failing to do here, is the real solution, but instead we get cynicism, patronizing and mythical hand waving as your proposed answers. 

Overall these are good guides for code style, with a few tweaks they'd be great for general purpose uses without being overly ridiculous but we're still at the ridiculous point years later. 

If you refuse to accept meaningful feedback just update your docs and shut this waste of years down and kill the noise.
