### ISSUE TITLE
3.8 side effect

### ISSUE THREAD

**Issue by Pdrevland** [airbnb/javascript#1884]
```javascript
const { a, ...noA } = copy; // noA => { b: 2, c:3 } 
```
This has a possible unwanted side effect as
```javascript
const a = 2;
const { a, ...noA } = copy; // =>SyntaxError: Identifier 'a' has already been declared
```

**Comment by ljharb** [comment]
That’s not a side effect, or even an effect, because it fails to parse - the language actively ensures it has *no* effect.

If this happens you’d simply rename either the original variable or the property you were destructuring.

**Comment by Pdrevland** [comment]
I think you fail to see the point
It doesn't fail to parse if a is not declared, the side effect is still there as you want noA and get a and noA. 
If it fails it is a very unwanted side effect. 

Using 5.1 I don't even see the need for it. It is a neat little trick though.

**Comment by ljharb** [comment]
The intention is to create a new object without “a”, without explicitly listing every other property you want copied from `copy`. The effect - not a side effect, the very wanted and intentional and primary effect - is to create a binding called “a” so that the value does not show up in the “noA” object. If you already have a binding called “a”, then you can’t do that unless you rename either the existing one, or the new one.
