### ISSUE TITLE
Template literal indentation

### ISSUE THREAD

**Issue by anthonator** [airbnb/javascript#1890]
I imagine this is a common enough issue that it's been reported before but I wasn't able to find anything in the open or closed issue log. Apologies if this is a duplicate.

Lines 7-13 in the snippet below throw an `indent` error. I can "fix" the issue by adding `TemplateLiteral` to `indent`'s `ignoredNodes` option. I'd ask that this fix be added unless there's a fundamental reason why this is a bad idea.

```
const build = font => `
  @font-face {
    font-display: ${font.display || 'swap'};
    font-family: ${font.family};
    font-style: ${font.style || 'normal'};
    font-weight: ${font.weight};
    src: ${
      font.formats.map(
        format => (
          `url("${format.file}") format("${format.type}")`
        ),
      )
    }
  }
`;

export default fonts => fonts.map(font => build(font));
```

**Comment by ljharb** [comment]
What's the error you get?

Ignoring the node is definitely not a great idea.

**Comment by anthonator** [comment]
<img width="743" alt="screen shot 2018-08-20 at 5 57 42 pm" src="https://user-images.githubusercontent.com/420061/44368963-a550e700-a4a2-11e8-9e4f-b407af111335.png">

**Comment by ljharb** [comment]
ah. since the contents of the template literal aren't *actually* indented, since they're not code (putting CSS in it is irrelevant), the indentation the rule wants is actually correct, even thought it looks gross:
```jsx
const build = font => `
  @font-face {
    font-display: ${font.display || 'swap'};
    font-family: ${font.family};
    font-style: ${font.style || 'normal'};
    font-weight: ${font.weight};
    src: ${
  font.formats.map(
    format => (
      `url("${format.file}") format("${format.type}")`
    ),
  )
}
  }
`;
```

This imo is just the cost of using template literals to write pseudocode like this :-/ ignoring the node seems fine for your use case, but in the general case, we recommend [CSS-in-JS](https://github.com/airbnb/javascript/tree/master/css-in-javascript), so this wouldn't come up.

**Comment by anthonator** [comment]
We actually are using CSS-in-JS. This is a utility for defining font faces we use in emotion.

Thanks for taking the time to discuss!
