### ISSUE TITLE
License files missing from older npm packages

### ISSUE THREAD

**Issue by dariagrudzien** [airbnb/javascript#1950]
@lencioni @dijonkitchen @ljharb Hello gentlemen, would you mind adding license file to eslint-config-airbnb-base@12.1.0 npm package? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Many thanks for the consideration.

**Comment by dijonkitchen** [comment]
Looks like this already exists: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/LICENSE.md

**Comment by ljharb** [comment]
It was added for v13 - 
https://unpkg.com/eslint-config-airbnb-base@13.1.0/LICENSE.md

It won’t ever be added to older versions; but it’s not actually necessary. The SPDX declaration in package.json has always claimed MIT, and no matter how paranoid your lawyer is, the lack of a license file doesn’t change that the intention was MIT. The code isn’t proprietary, in other words, because it’s authors publicly and incontrovertibly claimed it wasn’t.
