### ISSUE TITLE
[eslint-config-airbnb] Activate rule "require-await"

### ISSUE THREAD

**Issue by marcospgp** [airbnb/javascript#2013]
Since this guide is widely used as standard, turning on the rule "require-await", which prevents async functions that do not make use of "await", would be a good idea. Such functions are usually the result of refactoring.

**Comment by ljharb** [comment]
Absolutely it would not - that rule is horrifically bad, and `async function`s without `await` are *just fine*.

See the comment here: https://github.com/airbnb/javascript/blob/070e6200bb6c70fa31470ed7a6294f2497468b44/packages/eslint-config-airbnb-base/rules/best-practices.js#L317

I argued against eslint core including it as well; it arises from a fundamental misunderstanding of async functions as if they were like generators (they are not) - a generator without `yield` makes no sense, but an `async function` without `await` makes perfect sense.

**Comment by marcospgp** [comment]
Fair enough. But aren't the cases where you would want async without await edge cases?

**Comment by ljharb** [comment]
In no way are they edge cases. `async function` is a syntactic assurance that a function will always return a Promise - it can never throw or return anything else. That's its primary feature.

Being able to use `await` in it is a side benefit, and unfortunately one that's easily misused as well (unnecessarily making concurrent tasks block on each other, is the most common one). Needing `await` is the edge case, if anything.

**Comment by Izhaki** [comment]
> async function is a syntactic assurance that a function will always return a Promise - it can never throw or return anything else. That's its primary feature.

That is all good. But I guess this leaves us with the question:

> Why would you choose to have a function returning a promise if it does nothing asynchronously? 

And also:

> Could marking a function as asynchronous when it is in fact synchronous be the source of bugs and extra code complexity?

**Comment by ljharb** [comment]
@Izhaki For one, you don't need `await` to do something asynchronously, you could be returning `somethingElse()` which itself returns a promise; for another, you might be returning a promise solely to ensure a consistent API.

Yes, absolutely - anything could be a source of bugs, this is programming. The priority is to make your code convey your intent clearly, while also being correct. Forcing use of `await` does not ensure either.

**Comment by Izhaki** [comment]
I agree.

Recall that an async often requires support up the callee chain, both in terms of further async support and error handling.

I've been working on a promise-heavy code base and more often than not you want async functions to really be part of some async behaviour (which **includes** what you said - marking function as async because it returns a promise returned by another promise, with no await).

I landed on this issue because we had a function marked as async that was no longer async in any way or form, when I left a comment the response was "shouldn't there be an eslint rule for this" (we are using the airbnb config).

I'm not arguing the rule is always good, only that it is not as clear-cut as `horrifically bad`.

**Comment by barberdt** [comment]
Just got burned by a non-intentional `async` usage myself. The beauty of `eslint` is that rules, even those inherited from a project like this one, can be overridden. That being said, in overriding this rule choice, I found it pretty frustrating to simply see `(note: this is a horrible rule that should never be used)` without any explanation. Had to hunt down this issue to find some context. Sort of took away from the credibility of the project IMO. Some extra documentation explaining some of this there or maybe even just a link to this issue could help others in the future.

**Comment by ljharb** [comment]
@barberdt if you'd like to improve that comment with a PR, based on consolidating some of the justifications in this thread, that'd be appreciated.

**Comment by erlichmen** [comment]
I found that not calling await on an async function is an edge case and that in most cases you should call await.
For example the following code snippets:
```js
async function foo() {
  // do something async 
}

async function bar() {
	try {
		foo(); // await is forgotten here
    } catch (err) {
    	// handle code that will NEVER be called
    }
}

async function baz() {
	try {
		return foo(); // await is forgotten here
    } catch (err) {
    	// handle code that will NEVER be called
    }
}

async function baz2() {
	return foo(); // await is forgotten here
}

baz2().catch((err) => {
	// the err object has lost the originating context, the callstack will be hard to debug
});

```

Not calling await is mostly done when trying to-do fire-and-forget code which can be done using await by other means. From a personal perspective I rather have this rule enabled and comment out the rare cases when it is not needed.

**Comment by marcospgp** [comment]
I agree with @erlichmen . Two sources of hard to track down bugs are:

* Unintentionally async functions
* No await on intentionally async functions

**Comment by erlichmen** [comment]
Also I want to add, that no calling await is one of the reason for flaky tests that I found as the execution order is not stable and some tests are sensitive to that.

**Comment by ljharb** [comment]
@erlichmen indeed, not calling await or `.then` on a promise can cause problems if you expect to handle the errors.

However, "I find" does not match my experience. _i_ find that this rule is hugely harmful and disruptive, and causes far more problems than it fixes.

There's no way to avoid having developers and code reviewers having to learn how Promises and `async`/`await` work, and manually make the proper decisions - linting can't address that.

As for the call stack - changing your code to reflect *only one engine*'s flaws or incomplete enhancements (v8) is not a good strategy.

**Comment by erlichmen** [comment]
@ljharb cases where the await needs to be "skipped" are rare or might not be, it's up to the implementer and design to decide but every time that I don't see the await I want an explanation why. Without this rule I don't even know as an implementer that I'm missing something, the code might even run well do what it suppose to do but it is broken without me even knowing about it.
As for the shortcoming of V8, that is what most of us use, I don't even know if it's not by design this behavior or if even others implementation behave the same.

**Comment by ljharb** [comment]
@erlichmen the require-await rule doesn't cover this though. Literally all it does is ensure that every async function has at least one `await` - which doesn't solve your problem, and encourages a massive antipattern: an `await` where you might not need one.

v8 is used in node, but this guide targets code for browsers as well, and in browsers, v8 is just one of three engines.

**Comment by marcospgp** [comment]
How about updating the `require-await` rule to error only when an async function neither returns a promise nor awaits? If it's too hard to check whether it is returning a promise, error when it doesn't return anything at all.

Also, I would love there to be a rule that warned you when you are neither awaiting nor returning a promise from a function.

**Comment by ljharb** [comment]
In JavaScript, it’s impossible to statically know whether a thing is a promise.

There’s already a plugin and rules out there for typescript that provides this functionality.

**Comment by marcospgp** [comment]
@ljharb but then how can the tooltips in VSCode indicate that a method returns a promise? Isn't it a type like any other?

Anyway this is more of a thing to ask for in the eslint repo.

**Comment by ljharb** [comment]
@marcospgp that’s using vscode’s typescript language server.

Requiring you to await/.catch all promises would be a good rule. However, that’s impossible in JavaScript and most importantly, that’s not what require-await even remotely does. require-await is a horrible rule that shouldn’t exist and nobody should use.
