### ISSUE TITLE
arrow function return

### ISSUE THREAD

**Issue by niuchunling** [airbnb/javascript#2068]
confuse about this, why good & bad,  good  need return ?
![image](https://user-images.githubusercontent.com/11381775/62862467-73323800-bd38-11e9-9128-25b3fbcf9e06.png)

**Comment by ljharb** [comment]
Because in the "bad" example, an assignment (`bool = true`) is being used as if it were an expression. It *is* an expression, in the language, but conceptually it's a statement - and should be used as such.

Thus, the "good" example uses assignment inside a curly braced statement body of the arrow function, which properly returns `undefined` instead of the result of `bool = true`.
