### ISSUE TITLE
"import/extensions" rule is not documented (and I am also wondering about the justification)

### ISSUE THREAD

**Issue by Zamiell** [airbnb/javascript#2134]
Part 1:

The current Airbnb config has the "import/extensions" ESLint rule turned on. However, the reasoning for this is not given on the official style guide, and even the fact that the rule is turned on at all is not documented on the style guide. For example, there should be a blurb added to the [section on modules](https://github.com/airbnb/javascript#modules) that says something along the lines of:

```
// bad
import foo as './foo.js';

// good
import foo as './foo';
```

Question 1 - Can this be added / documented?

---

Part 2:

I searched around for some justification for this rule. In #1633, @ljharb says that 

> You're not supposed to use the extension there. The best practice for file extensions on imported code is to omit them, which is why our config requires that as well.

and:

>  the only time you should use extensions in require/import paths is if you're importing JSON files, or if you've made any nonstandard changes to allow requires of alternate extensions, like .css or .svg or .jpg. With .js, .jsx, or .mjs files, you should always omit the extension.

Question 2 - Why exactly is it best practice that they should be omitted? Is it just so that ES6-style module imports more-closely mimic the old, CommonJS-style imports? If so, that seems like a superficial reason.

And related: Even Mozilla has file extensions in their [official documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) for the import statement. So is there disagreement about what is best practice or is Mozilla in error here?

---

Part 3:

In #2121, some users bring up the fact that the "import/extensions" rule **breaks** code written for browsers without any transpilation. @ljharb counters with:

>browsers do not care about extensions whatsoever; only node does.

From a technical standpoint, browsers do not care about file extensions. But the fact of the matter is that on a lot of websites (or even most websites?), JavaScript files are served to the browser from a "public" subpath (or something similar) that maps to an internal file system. So, at least for a lot of websites,  **the file extension is required in the import statement** for ES6-style modules to work.

@ljharb also says:

> Regardless, you'll want to always use a bundler and transpile to CJS for the forseeable future.
> 
> If you make a different choice, you may want to override some of our linter settings, all of which assume you're following the best practice of using babel and a bundler.

I can understand that if most of the people in the JavaScript ecosystem are using a bundler, then the Airbnb default settings should be designed for people bundling. However... bundlers can handle file extensions just fine!

Question 3 - Would it make more sense to flip the rule and always require extensions? That way, any particular piece of JavaScript code will just work in **both** bundled-environments and non-bundled-environments.

---

Part 4:

As a final point here, I'd like to reflect on why Airbnb has decided to enforce ES6-style imports at all. The style guide gives the following justification in the modules section:

> Why? Modules are the future, let’s start using the future now.

But **why** exactly do we need to start using the future now? In my mind, it has to do with transpilation. The hypothetical, more-verbose version of the above sentence might read something like the following:

> Why? In the future, all browsers will support all of the latest JavaScript features. And when that day comes, you might feel the need to convert all of the modules in your application to ES6-style in order to get the code up-to-date. But there is a way to avoid this future workload - simply write your application with ES6-style modules **now** and use transpilation in the meantime until browsers catch up. One day, transpilation will be unnecessary, and your code will just work! Modules are the future, so let’s start using the future now.

If this is indeed the reason why we should start using the future now, then I can totally get on-board with the decision to require ES6-style imports as a ESLint rule - being future ready seems like a good thing. But if the end goal is to make transpilation unnecessary, then enforcing the "import/extensions" rule seems like a step in the **opposite direction**, because it forces code to be transpiled for perpetuity.

**Comment by ljharb** [comment]
Re part 1: yes, it would be great to document it in the guide.

Re part 2: For one, MDN isn't "official documentation", it's a wiki; it often does not reflect community best practices. As to "why", I've commented it many times in this repo's issues; we can iterate on that if a PR is submitted to document the requirement.

Re part 3:
> So, at least for a lot of websites, the file extension is required in the import statement for ES6-style modules to work.

This is inaccurate; browsers do not care whatsoever about file extensions. imports require exact URLs, which only need have file extensions if your webserver is somehow incapable of providing clean URLs via rewrite rules.

Separately, requiring extensions in no way makes things "just work"; anything that uses node globals requires transformation, and anything inside node_modules should not be naively served to the public, since node_modules contains tons of files you don't want to be hosting. It absolutely would not make sense to ever flip this rule.

Re part 4: There is no goal to make transpilation unnecessary; I do not foresee a time when transpilation will ever be unnecessary. The goal is maximum compatibility and correctness with minimal effort; using modern syntax and APIs, combined with transpilers, linters, and polyfills/shims, is the path to doing this.

Code already needs to be transpiled forever - only the target environments change.

**Comment by GreenImp** [comment]
I thought it might be worth re-assessing this rule as node does specify that for ESM the file extension is mandatory, to be in keeping with behaviour in browsers: https://nodejs.org/api/esm.html#esm_mandatory_file_extensions

I feel as though it should be changed to:
```
        "import/extensions": [
            "error",
            "ignorePackages"
        ]
```

Or maybe a warning, instead of error, so it doesn't break older scripts.

**Comment by ljharb** [comment]
This guide currently requires use of Babel, which precludes using the experimental native ESM implementation in node.

**Comment by GreenImp** [comment]
I hadn't realised that ESM was still in "Stability 1" on node, I was just aware that it now works without the `--experimental-modules` flag. So it's fair that you're not actively supporting the "standards" there yet; they could change.
A reasonable point about the use of Babel as well. Although in my case I'm running ESlint on the source code, so I imagine that whether I'm using Babel to compile it as a separate script makes it irrelevant for me?

Maybe in the future, once ESM in node is stable, it can be looked at again. I imagine a lot of people will follow the Node standards on that, once they're finalised.

**Comment by jalovatt** [comment]
For future discussions:
- ESM was moved up to Stable as of Node 15.3.x (November 2020)
- The auto-resolving behaviour we're used to be can be turned on for ESM via [`node --experimental-specifier-resolution=node`](https://nodejs.org/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm), though there are likely circumstances where you might still need to be explicit.
