### ISSUE TITLE
The `void` operator has legitimate use cases

### ISSUE THREAD

**Issue by slikts** [airbnb/javascript#2145]
I've written up the [use cases for the `void` operator][yes-void], but, in short, the main use case is for making non-value-returning arrow functions explicit while keeping them in a single line, so the `no-void` rule should be removed from the base config as an oversight.

[yes-void]: https://gist.github.com/slikts/dee3702357765dda3d484d8888d3029e

**Comment by ljharb** [comment]
It’s not an oversight; it is intentionally forbidden in every context. If you don’t want to return a value, don’t use the concise form.

**Comment by slikts** [comment]
I've looked through the issues and not found the rationale for including the `no-void` rule, and your comment also doesn't explain it or address the main use case (making void callbacks take up one line instead of at least three), so this issue should at least stay open to garner discussion.

**Comment by ljharb** [comment]
How many line something takes up isn't the issue; optimizing for line count is an anti-goal of readability.

While `void x` *can be used* as a braceless "do" expression that returns `undefined` (because that's how it happens to operate), that's not its purpose, and using it that way is a hack that does not increase readability or clarity. The thing that conveys "this arrow function doesn't return a meaningful value" is "it uses curly braces and lacks a `return` statement".

**Comment by clshortfuse** [comment]
I can see two other use cases for variable assignments. 

One is assigning a variable to `undefined` is actually a violation of ECMA spec. I've only seen Safari enforces this, and I've had instances where I get `ReferenceError`. Instead of `x = undefined`, you're supposed to do `x = void(0)`. That's because `undefined` is supposed to be a read-only interpretation of the internal Primitive. I guess it has to be that `undefined` isn't meant to be a value you can pass around.

It's not something I can tell exactly where and how Safari will throw errors because I wasn't able to stress test it, but it exists. 

The other usage is just to just be able to trim down lines with Promises where you want to shorthand the execution of a function, but don't want the result to be added to the promise chain:

````
return getNext()
  .then(incrementFn)
  .then(multiplyFn)
  .then(() => void logger.write('finished item')) // run async, ignoring result
  .then(() => buildGetNextRequest());
```

That just avoids having to write more lines like:

````
return getItem()
  .then(incrementFn)
  .then(multiplyFn)
  .then(() => {
    logger.write('finished item'); // run async, ignoring result
  })
  .then(() => buildGetNextRequest());
````

Assuming `logger.write` returns a Promise, using `void` would mean to not wait for the logger to write an entry before continuing to the next item in the Promise chain. But I will concede, it's just a matter of making it prettier and easier to read.

**Comment by ljharb** [comment]
@clshortfuse `undefined` can be reassigned, per spec, in every context except the global scope. `{ const undefined = 3; /* some code that uses `undefined` */ }` is perfectly valid. Every browser, as far as i'm aware, works this way. `void x` (no parens needed, since it's a unary operator, not a function) just evaluates `x` and then produces `undefined`.

`() => { /* no return statements */ }` and `() => void x` both result in `undefined` when invoked, but they convey very different developer intentions. The former conveys "this function does not return a meaningful value"; the latter (as well as `() => { x; return; }` conveys something closer to "it is very very important that this function return `undefined` and not `null` or `false` etc".

**Comment by clshortfuse** [comment]
@ljharb I think you misunderstood. I'm not talking about redefining the global `underfined`. That's valid since ECMA 3. I'm talking about reassigning a variable to the global `undefined`. I can't tell you exactly what version of Safari doesn't like this, since it was a while ago, but in my research as to why Safari didn't like `x = undefined`. It threw an error. I had to use `x = void 0`.

* `x = undefined` Set x to the value of the global undefined.
* `x = void 0` Set x to the result of void 0, which is the primitive value of `undefined`

When trying to figure that out the explanation to why Safari rejected the first one, I came across this article, which explains it: https://javascriptweblog.wordpress.com/2010/08/16/understanding-undefined-and-preventing-referenceerrors/

I'm not sure if the ECMA spec has changed since then (the article is 10 years old and based on ECMA 5), but I believe most, if not all, browsers guard against reassigning `undefined` which makes using this code obsolete in practice.

It makes sense as to why assigning a variable to `undefined` would be "bad practice" regardless of any current guards to changing the global variable. `undefined` isn't meant to be "held" as a value. But as for the alternative, it's  a bit weird to invoke a function to get back a value to then assign it to a variable. 

On the second point, I gave the example as to when it's important for an inline function to never return a value (prevent injecting itself into a Promise chain). MDN calls this practice [Non-leaking_Arrow_Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void#Non-leaking_Arrow_Functions). I think that's just a matter of preference against curly braces, but if I were to see `void`, I'd understand that it's an intentional guard against leakage. I honestly will probably start using it on my projects to clean up 3-line promise chain items down to one.

Also, in your `() => { x; return; }` example, it would be flagged as `eslint(no-useless-return)`, so if the developer intends wants to

>[convey] something closer to "it is very very important that this function return undefined and not null or false etc"

it currently wouldn't be possible in the current ruleset. Here, I can see `void` being good for that.

-----

The use case of `= undefined` versus `= void 0` doesn't matter to me. I don't support old versions of Safari anymore. Also, I find using void here to be confusing. IIFE execution also doesn't matter to me, since I feel it's such a unique situation that you could just add a `eslint-ignore` line.

But the prevention of leaking seems like a good idea. Unfortunately, there's no current eslint rule that targets just that, so if this package were to incorporate it, a change would have to start on the eslint side.

**Comment by paleite** [comment]
You could allow it as a statement, so it doesn't get confused with an expression. See https://eslint.org/docs/latest/rules/no-void#allowasstatement

**Comment by ljharb** [comment]
@paleite sure. but then it's a noop, and why would you want a line of code in your codebase that does nothing?

**Comment by paleite** [comment]
@ljharb could you explain what makes the expression a noop when using void? it _does_ run.

eg:
```
function f(){ console.log("hi"); }

void f(); // prints "hi"
```

**Comment by ljharb** [comment]
ha, fair enough that the invocation wouldn't be one :-) but in that case, `f();` would be identical, so what's the point of the `void`?

**Comment by paleite** [comment]
it guarantees that the invocation's return value is discarded. it's useful to signal that you called the function for its side effects and don't care about its returned value, for example when you're writing a async fire-and-forget callback-function, it will always return a Promise, but you don't necessarily want to await the result because it's Promise<void>

**Comment by clshortfuse** [comment]
I think what we want to avoid is people writing clever one liners like:

````js
let firstName = name?.split(' ')[0] ?? void alert('Full name required');
````

We can sometimes get performance obsessed and microoptimize instead of readable code or rely on our minifiers. It's a general bad practice.

That said, maybe within lambdas isn't all that bad. Promises are a good example. I've seen frameworks go from Node style callbacks `(...args) => (err, data)` with a function that returns null, then become a function that returns a Promise (while still supporting both). Explicit voids can be useful where we really don't want to consume the return value. Personally, I use a ts-based rule that allows void to explicitly specify we intentionally [have a dangling Promise](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md).

The other point is, is there a hard, fast rule we can come up where it's not more than one-offs? For example, I use `no-bitwise` because the possibility of missing a `&` when writing `&&` is more likely to occur than me interfacing with bitwise intentionally. But I do disable when I'm actually using bitwise. And in retrospect, I don't know how I feel about the TS rule I just mentioned now. It might be better to do an `eslint-ignore` for those dangling promises, since void doesn't actually do anything. Syntax for the sake of readability/skirt eslint rules is useless syntax. Comments exists for this. People reading my code later might think the `void` is doing something when it's really not.

Brainstorming, maybe within lambdas? Never preceding a return because that's micro-optimization. We don't need for assignment since `globalThis.undefined` exists. And definitely not in ternary since that's probably minifying in dev code. And in the rare case it's okay, use `eslint-disable-next-line` (but share with us what those cases are).

**Comment by ljharb** [comment]
@paleite the example you give would be a harmful practice - you *ALWAYS* need to at least `.catch` a Promise. _Nothing_ should be "fire and forget", ever.

@clshortfuse similarly, i'm not clear on why you'd ever want a dangling Promise.

I think occasional eslint overrides are perfectly fine, especially if there's a comment explaining why - including for this rule.

**Comment by clshortfuse** [comment]
>i'm not clear on why you'd ever want a dangling Promise.

Eh, more of a rarity. Basically when async functions that handle their own `try`/`catch`. I've used them for remote logging of errors within catch blocks, eg: `try { ... } catch(e) { void remoteLog(e); }`.  Basically latching a `.catch()` onto the function is useless since there's nothing to catch. That's probably because the function isn't is tapping into the `async`/`await` instead of being a sync function using an `IIFE`. Other examples are usually transient data or states, where error/failure is swallowed internally. Or they are one-off scheduling based wraps of promises (eg: setTimeout or throttling).

Still, that's getting off topic. My point is, even if you could design a "reliable" fire-and-forget, `void` isn't really doing anything. So, I'm not in favor of how the tslint rules does it. It's supposed to be used as an operator, not as a decorator/comment replacer. I can really only think of the arrow/lambda function, which MDN has good examples of practical usage:

>[Non-leaking Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void#non-leaking_arrow_functions)
>Arrow functions introduce a short-hand braceless syntax that returns an expression. This can cause unintended side effects by returning the result of a function call that previously returned nothing. To be safe, when the return value of a function is not intended to be used, it can be passed to the void operator to ensure that (for example) changing APIs do not cause arrow functions' behaviors to change.
>
>`button.onclick = () => void doSomething();`
>
>This ensures the return value of doSomething changing from undefined to true will not change the behavior of this code.

The return value context here is that if `doSomething()` returns `false`, it would be the same as `event.preventDefault()`. Here, `void` works as an operator, as intended, ensuring a `boolean` is never passed. It should give any other dev some pause before modifying it. The other point about API guards are good, though I haven't used it like that.

The point of just having:

````
button.onclick = () => { doSomething(); return;}
````

Would then yield another error of `no-useless-return`, which you'd adding an `eslint-disable` to anyway. Using `void` as an operator, it's clear that anything that the function should always have some sort of guard against returning a value. It's at the beginning of the statement, and not tacked on. If something changes and `doSomething()` becomes `doSomethingElse()`, or somebody slips in a ternary expression, it's expected to stay on. If I see `return;` at the end of the statement, I'd assume it's a mistake and/or missing something. If I see `void`, I figure it must be here for a reason (to then research and learn about how event handlers respond to return values).

---

That's the only usefulness I can see from it, in my opinion: ("Wow, a `void` statement! It must be important here!"). I don't see the usefulness for assignment of `undefined`.

**Comment by andyearnshaw** [comment]
> you ALWAYS need to at least .catch a Promise. Nothing should be "fire and forget", ever.

I'm not convinced this is true. Take the following function:

**Comment by andyearnshaw** [comment]
> you ALWAYS need to at least .catch a Promise. Nothing should be "fire and forget", ever.

I'm not convinced this is true, because it's possible to write Promise callbacks that can never reject. Take the following:

```javascript
const sleep = async (ms) => new Promise(resolve => setTimeout(resolve, ms));
```

or this:

```javascript
Promise.resolve().then(() => {
  // This will never throw even if an event handler fails
  myElementThatDefinitelyExists.dispatchEvent(new Event("my-event"));
});
```

**Comment by ljharb** [comment]
The former will throw if Promise or setTimeout is overwritten, and the latter can throw a number of ways, but sure, there may be rare exceptions. When those occur, and you’re informed enough to know about them, you can silently ignore the correct general advice, which is to *never* omit a catch on a promise chain.
