### ISSUE TITLE
Single-statement "blocks"

### ISSUE THREAD

**Issue by snan** [airbnb/javascript#2265]
In [Blocks](https://github.com/airbnb/javascript#blocks), the style guide recommends using braces with all multiline blocks.

But I think single-statement blocks are bad. The braces mean something, they're not just decoration.
It's almost like adding + 0 to all integers "for clarity", except, it's worse in a way because coming from lisp where when you see a `progn` or a `begin` you tense up because then you know there's gonna be side effects, which can be great when used correctly but can also be a source of bugs.

`{}` are the "progn" of JavaScript. Fantastic when you need to execute multiple **statements** as a block. Not so much when your code is a single statement that you just happened to have on a separate line.

    // good
    if (test)
      return false;

    // good
    if (test) return false;

    // bad
    if (test) {
      return false;
    }

    // good
    function foo() { return false; }

    // good
    function bar() {
      return false;
    }

    // good
    if (test) {
      frobnicate;
      return false;
    }

    // good
    function foo() { frobnicate; return false; }

    // good
    function bar() {
      frobnicate;
      return false;
    }

Function definitions have to have blocks, that's just part of the language spec. Similar to how a lambda works in lisp (where you can define `progn` as `lamba ()`).

**Comment by ljharb** [comment]
No idea what `progn` is, but I personally believe that curly braces must never be omitted - for clarity, and because omitting curly braces on a one-line if block caused [gotofail](https://blog.codecentric.de/en/2014/02/curly-braces/). Additionally, I'd strongly advise keeping only one statement per line.

Single-statement blocks are *in no way* bad in JavaScript, and in no way connote side effects. Virtually every JS codebase would violate a linter rule that forbade single-statement blocks.
