### ISSUE TITLE
Using accessors doesn't raise warnings

### ISSUE THREAD

**Issue by sirviot** [airbnb/javascript#2327]
The rule [24.2](https://github.com/airbnb/javascript#accessors--no-getters-setters) states that no getter or setters should be used, but using them in code doesn't trigger any warning or error in linter.

A file `test.js`:

```
export default class Test {
  get thing() {
    return this.thing;
  }

  set thing(aThing) {
    this.thing = aThing;
  }
}

```

I have the package `eslint-config-airbnb-base` version `14.2.0` installed. Should using accessors raise warnings or have I misunderstood (or failed to configure correctly) something here?

**Comment by ljharb** [comment]
It's impossible to raise warnings on *using* accessors, because it's impossible to statically know whether a property access is using a getter or not; we have not gone out of our way to programmatically prevent the creation of class `get` methods.

Not everything in a styleguide is lintable, and you can't ever abdicate the need for humans to review code - I'd say this falls into that bucket.

**Comment by sirviot** [comment]
OK, good to know. I hadn't read throught the whole styleguide and I was relying on the linter to keep my code in check. I was writing get and set methods for my class until I read about their contorversy in JavaScript, and only later noticed that they were discouraged also in the Airbnb styleguide.

Thank you, @ljharb, for your help.
