### ISSUE TITLE
Generator function

### ISSUE THREAD

**Issue by fundon** [airbnb/javascript#240]
Which is better?

## define Generator Function
```js
function* generator() {}
```

or

```js
function *generator() {}
```

## yield

```js
yield *generator;
```

or

```js
yield* generator;
```

**Comment by ssorallen** [comment]
Since the star is modifying the keyword and not the identifier or expression, I'd rule out `function *identifier` and `yield *generator`.

According to the [ES6 draft](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions), it's valid to include a space between the keywords and the stars similar to including a space between a function identifier and the parentheses:

```js
// Legal but off-style
function * test () {}
// ...
yield * blah;
```

Since this style guide prefers [no spaces](https://github.com/airbnb/javascript#functions) between function identifiers and the parentheses, I'd lean toward no space between the `function` and `yield` keywords and the stars. That seems to fit the current style:

```js
// Good
function* test() {}
// ...
yield* blah;
```

MDN also prefers this style in its docs:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function*
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*

**Comment by ssorallen** [comment]
The Chrome debugger prefers the latter example as well. When you reference the function definition again, it returns it spaced like that example:

```
> function *foo () {}
undefined
> foo
function* foo() {}
> function *bar() {}
undefined
> bar
function* bar() {}
```

**Comment by fundon** [comment]
Thanks, very detailed. :+1:
