### ISSUE TITLE
JSPerf shows that concat method to copy an array is faster than slice

### ISSUE THREAD

**Issue by caherrerapa** [airbnb/javascript#243]
According to jsperf [].concat(array) runs way faster than Array#slice in chrome and similar performance for other browsers

**Comment by kevingimbel** [comment]
@caherrerapa When stating facts like "runs way faster" you should provide some data, in your case best a link to JSPerf test case.

**Comment by caherrerapa** [comment]
@kevingimbel sorry my bad

http://jsperf.com/converting-arguments-to-an-array/23 (Revision 23 - November 2014)
the test used to say the slice is the preferred is based on the revision http://jsperf.com/converting-arguments-to-an-array/7

Please correct me if im wrong

![converting_arguments_to_an_array_ _jsperf](https://cloud.githubusercontent.com/assets/1084920/6186180/e1122176-b3a8-11e4-80f4-53d430f5642d.png)

![converting_arguments_to_an_array_ _jsperf](https://cloud.githubusercontent.com/assets/1084920/6186211/3ecac854-b3a9-11e4-85b0-940fb39f899a.png)

**Comment by goatslacker** [comment]
We're favoring clarity and readability > performance in this case. For most user applications this is completely acceptable since JS is already fast enough, however, if you're building a Fast Fourier Transform then you should probably optimize for performance.

That said, `[].concat(array)` is pretty readable IMO as well, I don't have a strong opinion on this. @hshoff

**Comment by goatslacker** [comment]
#157
