### ISSUE TITLE
omitting extension is a footgun

### ISSUE THREAD

**Issue by jimmywarting** [airbnb/javascript#2469]
> 10.10 Do not include JavaScript filename extensions eslint: import/extensions

this is bad if you ever choose to convert to ESM spec

**Comment by ljharb** [comment]
That’s not something you should ever do (convert to native ESM).

It’s slower, and has lots of drawbacks. This guide requires you to use Babel, so all its advice assumes you’re doing so

**Comment by jimmywarting** [comment]
> It’s slower, and has lots of drawbacks

it has also other benefits like working with nodes new HTTP import, Deno and Browsers

> This guide requires you to use Babel, so all its advice assumes you’re doing so

That may be the case but only b/c you are using babel doesn't it mean we should follow best practices 
ryan dahl regrets the hole extensionless pattern https://youtu.be/M3BM9TB-8yA?t=836

it makes it easier to drop the hole babel eventually if you decide to drop it later when you don't need it

**Comment by Josh-Cena** [comment]
The problem with sticking to Babel and the good old CJS is that ESM is not backward-compatible. With more libraries migrating to ESM-only (which I believe is a justified trend in moving forward), you can no longer `require` those libraries. `await import()` is much less ergonomic than the lexical `import` because asynchronousness is contagious and could at some point lead to the need for top-level await. Eventually, as you try to make your CJS library play nicely with ESM deps, you realize it would be much simpler to migrate your own codebase to ESM. While Airbnb style guide followers can abide by the belief that "That’s not something you should ever do", you can't hold the community back from going forward.

Transpiling external dependencies with esbuild (don't even know if Babel works in this case) remains as an option, though, but that doesn't scale and yields little DX benefits

**Comment by ljharb** [comment]
ESM isn’t forward, that’s the problem. In many ways it’s backwards.

**Comment by Josh-Cena** [comment]
Maybe I shouldn't say _forward_—anyways this doesn't imply an _improvement_ (although in some ways this can be) but just a _temporal movement_.

From a pragmatic view though, is transpiling the deps as a post-build step the only way to ergonomically make ESM packages interop with CJS?

**Comment by ljharb** [comment]
Since most people won't count "manually" as ergonomic, yes.

Build steps are required for modern web dev anyways, and will be for the foreseeable future, for many many reasons. Optimizing for avoiding a build step is like optimizing for fewer lines of code - it doesn't actually achieve anything useful.

**Comment by jimmywarting** [comment]
> Build steps are required for modern web dev anyways, and will be for the foreseeable future, for many many reasons.

I like build-less dev setups, they are so much faster while developing and not having to compile stuff all the time all the time.
only when i make a release, then i compile to lower language to support older browsers. it's also easier to debug.
