### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Yatin-kathuria** [airbnb/javascript#2515]
- In react readme.md , I don't able find the back to top link like we have in javascript readme. Is their any specific reason ? It will be good if we have a back to TOC.
- I didn't found any section for `no-await-in-loop` eslint rule. It will be a great add on in the `Iterators and Generators` section.

Let me know If any above point is valuable to this repository .I am happy to work on that

**Comment by ljharb** [comment]
Every markdown file on GitHub now has a table of contents under the button on the top left; i don’t think the main guide needs the link anymore, in fact (but it’s fine to leave it as it is)

The linter config already doesn’t allow async functions, because of regenerator-runtime, so I’m not sure why we’d need to explain ni-await-in-loop.
