### ISSUE TITLE
Needs clarification for one of the rules

### ISSUE THREAD

**Issue by vladyslav-karpus** [airbnb/javascript#2672]
A [rule](
https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless) says to use function declarations for components. So I have questions.

1. Why do we need to use function declaration rather than arrow function for stateless components?
2. If I have a state (useState), should I use a function declaration as well?

**Comment by ljharb** [comment]
For 1, because arrow functions don't have explicit names, only inferred ones, and that inference will surprise you when you inevitable do something like `const Foo = React.memo(() => <div />);`.

An SFC is stateless even if it uses `useState` - but it's the fact that it's a *function*, not whether it has any form of state, that necessitates it being a normal named function.
