### ISSUE TITLE
Remove redundant dependencies

### ISSUE THREAD

**Issue by megahertz** [airbnb/javascript#2701]
Maybe that's time to drop object.assign and object.entries dependencies? The airbnb config packages are pretty small by itself but these packages are huge: 
- object.assign@4.1.4 (8 deps, 1.25mb, 102 files)
- object.entries@1.1.6 (47 deps, 3.37mb, 1932 files)

I think that's not actual anymore in 2023 since Object.assign was added in node.js v4, Object.entries in v7. 

So, this change could make a typical CI task a bit faster.

There was a closed PR in 2019 https://github.com/airbnb/javascript/pull/2111, I can create a new PR if that makes sense.

**Comment by ljharb** [comment]
These things still occasionally have bugs that need fixing in modern engines, and install size isn't really important. (also 1-3MB is in no way "huge" - and your size and file counts are excluding that most of it is due to those packages' transitive deps, which are already present in most large apps, and thus are often zero cost)

**Comment by ljharb** [comment]
@livinglogic-nl at the moment I don't know of any specific bugs in the *latest* version of engines with these two - but `Object.assign`, in particular, had bugs in v8 (Chrome and node) up until around node 5, and Firefox 37-39. The important thing is to not have to care about what these bugs are - to delegate that knowledge to the polyfill packages.

**Comment by livinglogic-nl** [comment]
@ljharb Good to hear that it seems to be ok these days!
I can see how keeping these dependencies gives you confidence in the quality of this solution.
At the same time, I do think TC39 has helped javascript to become more than it used to be. Removing these polyfills would pay tribute to that.

**Comment by ljharb** [comment]
I'm on TC39, and I'm glad to hear that - and I think keeping them is the better choice.

**Comment by livinglogic-nl** [comment]
Just out of curiosity... will there ever be a time you would decide otherwise? What is the criterion to start using what TC39 accomplished? I totally understand being careful with new features. But this functionality seems to be implemented just fine for quite some time now. What is the value of evolving javascript if the better choice is to just hold on to 8-year old polyfills?

**Comment by ljharb** [comment]
The purpose of evolving the language isn't to remove the need for polyfills - polyfills are a part of that evolution itself.

**Comment by ljharb** [comment]
That said, the required node versions here support object spread, so I've removed `object.assign` in fd96a4fd57be26d4d9d2f2d24b373a2df7c23548.

I think this can be closed.
