### ISSUE TITLE
Why is whitespace set to 2?

### ISSUE THREAD

**Issue by icirellik** [airbnb/javascript#439]
I did a quick search a couldn't find another issue on this topic, just wondering if there is any compelling argument for using 2 spaces over 4. Being a long time node developer, I just accepted that it won the war long before I joined.

My question is due to the fact that my workplace is primarily a Java shop and we are quickly switching over to node/react and a war has broken out over 2 vs 4 spaces (Oh how I long for the days of tabs vs spaces.)

Just wondering if someone could provide any insight as to how your team arrived at 2.

**Comment by hshoff** [comment]
Hi @icirellik, thanks for checking out the guide. 

At Airbnb we have style guides at a language level (JS, Ruby, Java, etc.) vs. having a style guide that follows the same spacing rule across all languages. Regardless of how your team chooses to implement and follow a style guide, the important part is consistency. 

As a team we just happened to stick with soft-tab set to 2-spaces. Mostly because by the time we got around to writing our style guide down almost all of it was already soft-tabs with 2-spaces.

Hope that helps! :+1:
