### ISSUE TITLE
JSON declaration - single vs. double quotes

### ISSUE THREAD

**Issue by dthree** [airbnb/javascript#441]
JSON is standardized to use double-quotes, to the degree that this would not be considered standard JSON and would error in a JSON parser.
```js
var foo = {
 'bar': 'foobar'
}
```
However, to keep consistent with single-quoting strings, wouldn't this create a conflict?

I suppose I could use double-quotes for JSON objects only, however this is then going to create an inconsistency in my linter if I specify single-quotes as the preference.

Sugesttions?

**Comment by ljharb** [comment]
Why is your JS linter running on JSON files?

**Comment by dthree** [comment]
It isn't - I was thinking about inline object / JSON declarations given in .js files. I guess the rules of strict .json then don't apply to inline JSON in a .js file? This may be what I was missing.

**Comment by ljharb** [comment]
These are rules for JavaScript, not for JSON (which is not JavaScript, and is just a string serialization format that shouldn't be handwritten anyways). JSON is a string, not an object - do you have an inline JSON string? In other words, if it's an inline JS object, then JSON rules don't apply, because it's not JSON.

**Comment by dthree** [comment]
Ok silly me. Didn't realize that. Thanks!
