### ISSUE TITLE
Boolean("false") parses to true

### ISSUE THREAD

**Issue by tuhlmann** [airbnb/javascript#531]
In section "21.6 Booleans" you advice to use `Boolean(x)` to parse a value into a boolean.
Please note that parsing mostly any String results in `true`:

```
Boolean("false")
=> true
```

`null, undefined and ""` parse to `false`.

**Comment by ljharb** [comment]
That's not for parsing a value - that's for coercing a value. Parsing a string into a boolean is an undefined operation - you need to implement it yourself. If you want the truthy value that is the string "false" to coerce to `false`, you'd need to write a function that does that conversion for you.

**Comment by tuhlmann** [comment]
Thanks for the clarification, after looking at the example again I see the difference.

**Comment by hshoff** [comment]
Hi @tuhlmann, to follow up, just because I was typing this as this closed :smile: 

This is expected behavior as defined in [#15.2](https://github.com/airbnb/javascript#15.2)

> Strings evaluate to **false** if an empty string `''`, otherwise **true**

We use the [Comparison Operators & Equality](https://github.com/airbnb/javascript#comparison-operators--equality) to outline the behavior of the `ToBoolean` abstract method.

:beers:

**Comment by tuhlmann** [comment]
@hshoff Thanks for the clarification.

For a seasoned Java developer Boolean(something) looks awefully familiar. In Java `new Boolean(str)` or the preferred static method `Boolean.parseBoolean(str)` do exactly this parsing stuff.

I guess that's where the confusion came from. Maybe a short note in this section would avoid this trap, saying this does not parse, but coerce...
