### ISSUE TITLE
Style autofixing

### ISSUE THREAD

**Issue by hshoff** [airbnb/javascript#535]
Just a placeholder for now. Would love to take linting to the next step and autofix rule violations.

**Comment by goatslacker** [comment]
I'll just leave this here: https://github.com/jshint/fixmyjs

**Comment by justjake** [comment]
Eslint has some fixes now I think.

**Comment by hzoo** [comment]
JSCS has had autofix since 1.12.0 (supporting all whitespace rules, and a few others). We're trying to figure out how to potentially fix all rules and working hard now on https://github.com/cst/cst and integrating that into JSCS.

And yeah ESLint has recently added support for it as well for the last few releases. The fixable rules have `(fixable)` on the rules page.

The future of linting is exciting :smile:!
