### ISSUE TITLE
ES2015 has multi line strings

### ISSUE THREAD

**Issue by swist** [airbnb/javascript#573]
Have you encountered a significant performance hit when multiline strings wrapped in backticks as opposed to concatenating them?

**Comment by gillesbourgeat** [comment]
Hello,

You can test here.
http://jsperf.com/ya-string-concat/32

**Comment by ljharb** [comment]
a) performance of new features isn't useful to test, because they're almost never optimized
b) babel transpiles template strings to normal string literals, so no performance hit could possibly exist at runtime when using babel
c) unless you're generating millions of string literals every second, your app will likely never be impacted one way or the other
