### ISSUE TITLE
linter won't let me use strict mode but still forces me to use 'let'

### ISSUE THREAD

**Issue by mezod** [airbnb/javascript#587]
Hello, I have a catch-22 situation.

I need to have a variable in a for loop 

    for (obj of usersArray) {
        delete obj.password;

        obj.listsCount = yield lists.countByUser(obj.id);
        obj.logsCount = yield logs.countByUser(obj.id);
      }

First, the linter won't let me use 'let' in for(let obj of usersArray) because 'the obj doesn't change'. Then, I try to declare var obj outside the for loop, and the linter (no-vars) forces me to use let. However, to use let in node 4.1.0 you need to be in strict mode which is forbidden by the linter (no-strict). What am I supposed to do here?

node v4.1.0

**Comment by ljharb** [comment]
You should be using `const` since you don't reassign `obj`. The reason we disallow `use strict` is because babel provides that automatically in `class` and module code.

In addition, node/v8 currently doesn't have complete let/const semantics in sloppy mode. You will want to be using babel, even in latest node.

Absent using babel, you'll need to override the `no-strict` rule for your project.

**Comment by mezod** [comment]
I started by using const. But apparently, if I use const, only the first element in the array gets the counts :/

**Comment by ljharb** [comment]
@mezod yes, that's a result of v8's buggy/legacy let/const implementation, and yet another reason to use babel.

**Comment by mezod** [comment]
Ok, thank you @ljharb :)
