### ISSUE TITLE
Thoughts on "Use dot notation when accessing properties"

### ISSUE THREAD

**Issue by AlicanC** [airbnb/javascript#642]
This is my rule for accessing properties:

> If the object has properties that is not accessible with dot notation, use subscript notation. Use dot notation otherwise.

So:
```javascript
const objOne = {
  'facebook': 'no idea',
  'google-plus': 'no idea',
};

objOne['facebook'] = 'thanks';
objOne['google-plus'] = 'no thanks';

const objTwo = {
  'facebook': 'no idea',
  'googlePlus': 'no idea',
};

objTwo.facebook = 'thanks';
objTwo.googlePlus = 'no thanks';
```

With Airbnb style, you have to write like this:
```javascript
obj.foo = true;
obj.bar = true;
obj['foo-bar'] = true;
obj.baz = true;
obj['foo-baz'] = true;
```

This looks very ugly to be honest.

---

My suggestion is this (which is also different from my own rule):

> Prefer dot notation when accessing properties. Only use subscript notation when you have to. If you used subscript notation when accessing a property, use subscript for other all cases.

So:
```javascript
function foo(providers) {
  const myProvider = 'google-plus';
  
  if (providers.facebook) { // This is okay
    // ...
  } else if (providers[myProvider]) { // This is okay
    // ...
  }
}

function bar(providers) {
  if (providers['google-plus']) { // This is okay
    // ...
  } else if (providers['facebook']) { // This is okay
    // ...
  }
}

function baz(providers) {
  if (providers['google-plus']) { // This is okay
    // ...
  } else if (providers.facebook) { // This is not okay
    // ...
  }
}

function boo(providers) {
  if (providers['facebook']) { // This is not okay
    // ...
  }
}
```

**Comment by ljharb** [comment]
This would involve modifying the [`quote-props`](https://github.com/eslint/eslint/blob/master/docs/rules/quote-props.md) rule [here](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/style.js#L94#L16) (which is currently disabled, but shouldn't be) to use the "consistent-as-needed" config option instead of the one we currently should be requiring which is "as-needed".

"looks very ugly" is a subjective thing, and personally I very much prefer the aesthetics of only invalid identifiers being quoted. (Our preference for camelCase also means that `googlePlus` would be a better property name than `google-plus` when possible.)

In addition, the more quoted properties you have the slower your code will be - very few versions of very few engines optimize "hardcoded string literals in bracket access" to be as fast as "dot access".

I will definitely enable this rule regardless. I'll leave this open so people can offer their opinions on "as-needed" versus "consistent-as-needed", although that would only apply to object literals - property access would remain "as-needed".

**Comment by ljharb** [comment]
Dot notation should be used at all times, when possible. Thanks for the discussion!
