### ISSUE TITLE
[base/rules/es6.js] Why are all rules on error?

### ISSUE THREAD

**Issue by jcalfee** [airbnb/javascript#853]
Most of these rules need to be changed from error `[2,...` to warn `[1, ...` ...

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/es6.js

**Comment by ljharb** [comment]
They are errors intentionally. Warnings are mostly useless, since they are easily ignored. If it's not an error, it's not enforced.

**Comment by jcalfee** [comment]
Ok, but I think your mixing personal problems with your software..  If users want to have a policy of no warnings they can do that.   Your project would be more useful if it benefited from the warning feature.

**Comment by lencioni** [comment]
@jcalfee Thanks for the feedback! I don't understand how it would be more useful but I would like to--can you help me?

**Comment by jcalfee** [comment]
With all the warnings set to error, I can't see errors.  I'm viewing other peoples projects and code so it is not possible to fix them.  It makes the most since to put any thing that does not break at runtime on warning and anything that will create an error at runtime on error.

**Comment by jcalfee** [comment]
We have c++ coders using different styles on our project too.. It is not a big deal to me to read their code.  I do like to spot errors though, I am modifying that code.

**Comment by ljharb** [comment]
Style issues may not break on runtime, but in an interpreted language (without a compiler to catch many of these kinds of errors at build time), it's critical to catch these errors at build time. Everything we consider enforceable here is just as dangerous in a codebase - whether it interferes with parsing or not.

Linters should be employed at a project level, not across projects, so I'm confused why you're seeing errors in other people's projects.

**Comment by jcalfee** [comment]
I noticed the warning level was utilized.  Using that would mean that I could use your lenting rules to edit javascript in our project written by the c++ team (where their coding style and editor is setup differently).  Otherwise it is not useful at all when looking at those files.

**Comment by ljharb** [comment]
My suggestion would be for that project to have its own linter rules set up, so that all the developers using the project can benefit, rather than applying your personal linting rules to a project.

**Comment by jcalfee** [comment]
it is the same project

**Comment by lencioni** [comment]
@jcalfee Thanks for taking the time to explain things to me. I think I have a clearer understanding of your situation now.

**Comment by jcalfee** [comment]
The other case we have is old code.  We don't change it much so it is probably wiser to leave it alone and maybe wait on automated code formatting solutions rather than fix it by hand.  The most pressing case is the new code from the VI c++ gurus that write javascript in our project.  We are editing that more often. 

Warnings might help someone else that wants to use your rule set on old code to make a transition.  A co-worker informed me that webstorm shows all your rules as warnings anyway.  It my editor Atom and its eslint plugin that is showing it appears in your rule set.

**Comment by ljharb** [comment]
You can use an `.eslintrc` per-directory to disable, or warn instead of error, on old code.

In general, if you'd like to change any of our config settings, please feel free to either fork the project and do so, or, use an `.eslintrc` to override anything you like!

**Comment by jcalfee** [comment]
I use this work around to move the error level to warning.  I'm sure it mislabels things, but in my coding I don't see too many warnings (after the patch) that should be errors so this works great for me.  It does not effect other users.
```bash
# Work-around, move everything from error to warn:
find node_modules/eslint-config-airbnb -name '*.js'|xargs sed -i 's/\[2,/\[1,/'
find node_modules/eslint-config-airbnb -name '*.js'|xargs sed -i "s/': 2/': 1/"
```

**Comment by BohdanTkachenko** [comment]
I also think that it could be better if not all rules to be like errors. My point is following: I'm using eslint in Atom to see if I have any errors in my code and also I use Webpack with eslint-loader and NoErrorsPlugin, so when there is any ESLint error in my code - it does not compiling, which is good, because it saves a lot of time when it detects an error that makes unable for my code to run. But the thing is that sometimes when developing I need to insert console.log, or I need to quickly add an element to array to test something (and sometimes I'm doing it too quickly and not adding comma in the end of a line) and in this case Webpack will just not compile my code because ESLint tells that there are errors. But from my point of view they are more likely warnings, not errors, because code will work, but it will be just not perfect at this point.

I think that it would be much better if all critical rules which can detect places that can break something to be like errors, but for other ones that are more like stylistic - everything that is not good to commit, but that will work - to have warning level, so it will more like informative. 

BTW, for CI systems you can set --max-warnings 0 flag for eslint and it will fail build even if there are any warnings detected, so it is possible setup it correctly when building project, but it is not so usable for development in some cases. What I'm doing right now is just redefining some rules in my local .eslintrc, setting some rules to warning instead of error

**Comment by ljharb** [comment]
@BohdanTkachenko all rules are critical, and ALL rule violations should break the build, of any kind.

If you disagree, you're welcome to fork and/or override anything you like and make them into warnings.

**Comment by BohdanTkachenko** [comment]
@ljharb I completely agree with you and code that does not pass linter should never be commited to GIT and it should always break build and this project is awesome in this task - it really helps to find bad code before it is commited. I mean only the situation when you work with code locally and you need something like console.log for debugging only. Setting different error levels for different rules will just allow to setup linter in different ways, but it still will break builds with bad code.

**Comment by ljharb** [comment]
In that case, don't you simply ignore the linter warnings? The linter should run pre-push, but it's kind of silly to have your local dev build process fail based on linter warnings imo.

**Comment by BohdanTkachenko** [comment]
The thing is that in my case I have webpack plugin that kind of saves some time for me by checking if there are any critical ESLint errors (for example, wrong syntax), so I know about an error before I open my app in a browser. 

Btw, also another point. When I edit code and my code editor lints file and reports some error in yellow color, I visually see that it's something not so important, and I can come back to fix it a bit later, if I'm debugging something. But if I see red color, then it's something that can break build or cause some problems even when debugging, so I need to fix red ones immediately to be able to continue to debug.

Probably it is just easier just not to use this NoErrorPlugin for Webpack (it's not so important, just makes life a bit easier), but I just was interested, maybe you and other maintainers of this repository find my point of view convincing and I can work on PR.

![vico_jsx_ __users_bohdantkachenko_projects_vico](https://cloud.githubusercontent.com/assets/929598/16637989/c6a3a4aa-43e3-11e6-8435-704d37e247cf.png)

**Comment by ljharb** [comment]
That's commonly and easily achieved with an editor plugin - there's no need to put that in webpack.

In general though, you shouldn't continue until you've added the semicolon on line 56. The idea that some linter errors are "less important" is the one I have a problem with. A missing semicolon should break your entire build and halt everything just the same as a syntax error.

**Comment by BohdanTkachenko** [comment]
Yeah, I know what do you mean. I also like an idea that when you build a project, all rules are important and even silly console.log can make problems in old IE, for example. But I mean that in most cases when debugging your code, some of the rules can be ignored because they'll not cause any problems in your environment.

But I rather agree with you, because each developer or project has different environments and it is not possible to tell in which environment which rules are critical and which are not.

Probably the best solution is to create a new config which extends this config, but just overrides error levels for some of the rules and use this config only in some projects where it's acceptable.

Thanks for your comments!

**Comment by alexanderjarvis** [comment]
@ljharb there is a difference between breaking a build and cleaning up your code before committing it. I also hit this exact issue recently and it's doing my head in (seeing red errors in Atom alongside Flow errors and not knowing which one is which). Setting --max-warnings 0 to treat warnings as errors for CI seems to be most sensible. The issue is not being able to quickly write code and then cleanup, because everything is red until you write perfect code.

**Comment by ljharb** [comment]
Part of being able to write code quickly is unconsciously writing correct code quickly. That comes with time and practice, and linter rules help whether they're warnings or not. A Flow error is just as critical as any other linter error, and vice versa, and all need to be fixed.

**Comment by alexanderjarvis** [comment]
I agree with you but I'm much happier now that I don't have red errors in Atom (using a fork) :)

Fundamentally I think making all rules errors was the wrong decision spurred on by wanting to make the build fail.

Especially where the lint errors complain about minor things such as indentation, whereas in a compiled language you'd of course expect a type error to fail the build.

**Comment by ljharb** [comment]
Indentation inconsistencies should fail the build. If a coder was sloppy about indentation, who knows what other (often unlintable) bugs they were careless enough to let slip through.

**Comment by alexanderjarvis** [comment]
Exactly, fail the build where warnings are treated as errors.

**Comment by ljharb** [comment]
I'm saying it should be granted the same level of severity as any other error. Marking some things as merely "warnings", even if they fail the build, encourages devs to think of them as somehow less severe or less important - which they are not.

**Comment by davidqqq** [comment]
And here I am struggled for 2 hours trying to find out how to turn errors to warnings.

**Comment by MNF** [comment]
To separate differential types of rules you can use Prettier for code formatting concerns, while letting your linter focus on code-quality concerns.
E.g. put at the end  of .eslintrc.json:

{
  "extends": ["prettier"]
}
See more details/options  in https://prettier.io/docs/en/integrating-with-linters.html, .

**Comment by ljharb** [comment]
Formatting is a code quality concern, and prettier is just an alternative to some of the rules this guide currently enforces (eslint hasn’t autofix too) - the underlying ideology is unchanged.
