### ISSUE TITLE
import/no-unresolved thrown when using app-module-path package

### ISSUE THREAD

**Issue by brendanvinson** [airbnb/javascript#859]
We're currently using [app-module-path](https://www.npmjs.com/package/app-module-path) to make our import paths saner. Since the update to 2.0, I've been getting import/no-unresolved errors in my linter output when the modified paths are used.

I can't find this rule in the eslint docs, is this something that is specific to airbnb? I've set this to warn status so it doesn't impact me as much, but would like to know if a fix can be implemented.

**Comment by tleunen** [comment]
This comes from the eslint import plugin. In your case, you should probably disable the rule since you're using a custom way to specify your import paths.

**Comment by tleunen** [comment]
Also, it seems like your module is not really required.
You could achieve the same thing by using the environment variable `NODE_PATH` before running your script. 

With this `NODE_PATH=./src`, you can require everything inside `src`, and because it's a native node thing, I guess the default Node resolver will be able to resolve the files.

**Comment by lencioni** [comment]
This rule comes from (eslint-plugin-import)[https://github.com/benmosher/eslint-plugin-import], which you can tell from the rule name because the part before the `/` refers to an eslint plugin of the same name.

You can probably [configure the node resolver](https://www.npmjs.com/package/eslint-import-resolver-node) to do what you want. If that doesn't work, you could probably add a [resolver](https://github.com/benmosher/eslint-plugin-import#resolvers) for this.

**Comment by andrewsuzuki** [comment]
This was my solution (add to your .eslintrc "settings" entry if it already exists):

```javascript
  "settings": {
    "import/resolver": {
      "node": {
        "moduleDirectory": [
          "node_modules",
          "app"
        ]
      }
    }
  }
```

There are more options besides "moduleDirectory", see [here](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/node).
