### ISSUE TITLE
Elaborated ant turned off rules

### ISSUE THREAD

**Issue by vsemozhetbyt** [airbnb/javascript#908]
Soryy, I've just started to use `eslint-config-airbnb-base` and rules as this puzzle me:

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/best-practices.js#L117-L122

What's the point in elaborating the rule parameters if the rule itself is turned off?

Is this all about [this merging scheme](https://github.com/eslint/eslint/issues/6361), so that, if a user just turns the rule on, all the recommended parameters would be ready?

**Comment by ljharb** [comment]
It's multiple things - certainly that the recommended parameters are ready - just like some users choose to disable rules we enable, they may enable ones we disable, and the guide still has preferences even if the linter isn't enforcing them.

However, it's also to document them, so that if later there's discussion to enable the rule, that discussion can have the full context of all the options around that rule.

**Comment by vsemozhetbyt** [comment]
Thank you.
