### ISSUE TITLE
A question about react stateless function

### ISSUE THREAD

**Issue by ehrudxo** [airbnb/javascript#937]
In the link
https://github.com/reactjs/redux/issues/1176

I found that stateless function is slow because of rendering, so they recommend React function even if it is stateless.

Is there any other reason you suggest stateless function?

**Comment by ljharb** [comment]
State is toxic and adds cognitive overhead, and it should be avoided whenever possible. SFCs aren't better because they're faster - although in the future they *will* be faster - they're better precisely because they're stateless.

**Comment by ljharb** [comment]
In addition, "performance" should always be the last concern, prioritized far after maintainability, clarity/cleanliness, elegance, and after things are tested *and* benchmarked. A style guide only recommends one option for performance when all options are otherwise equal - a rare occurrence.

**Comment by jimbolla** [comment]
If you're measuring an actual perf loss due to re-renders of functional components, you can wrap them with recompose's [pure](https://github.com/acdlite/recompose/blob/master/docs/API.md#pure), [onlyUpdateForKeys](https://github.com/acdlite/recompose/blob/master/docs/API.md#onlyupdateforkeys), or [onlyUpdateForPropTypes](onlyUpdateForPropTypes).

**Comment by ehrudxo** [comment]
@ljharb thanks a lot for your comment.
